baseURL = "http://example.org/"
languageCode = "en-us"
title = "Enroll Documentation"
showLicense = true
showToc = true
relativeURLs = true
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
