# frozen_string_literal: true

source 'https://rubygems.org'

# Declare your gem's dependencies in ui_helpers.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]

gem 'resource_registry',  git:  'https://github.com/ideacrew/resource_registry.git', branch: 'trunk'
gem 'financial_assistance', path: '../financial_assistance'

gem 'rspec-rails',            '~> 5.0.1'
gem 'capybara'
gem 'byebug'
