import "core-js/es6/object";
import "core-js/es7/object";
import "core-js/fn/object/values";
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
import "core-js/es6/array";
import "core-js/es6/promise";
import "./append";
import "./foreach";