key: :enterprise
namespaces:
  - key: :tenants
    namespaces:
      - key: :dchbx
        settings:
          - key: :organization_name
            default: DC Health Benefit Exchange Authority
          - key: :owner_account_name
            default: admin@hbx_org.com
        namespaces:
          - key: :sites
            namespaces:
              - key: :primary
                settings:
                  - key: :url
                    type: URL
                    default: https://shop.openhbx.org
                  - key: :title
                    type: string
                    default: ACA SHOP market
                  - key: :description
                    type: string
                    default: shop market
                namespaces:
                  - key: :environments
                    namespaces:
                    - key: :production  
                      namespaces:
                        - key: :features
                          namespaces:
                            - key: :enroll
                              settings:
                                - key: is_required
                                  description: Feature must be required if true
                                  default: false
                                - key: is_enabled
                                  description: Feature must be enabled if true
                                  default: false
                                - key: alt_key
                                  description: Shortened Key reference to be used in Registry
                                  default: ea
                                - key: :title
                                  description: Name for this setting that will appear in the UI
                                  default: Enroll Application Component
                                - key: :description
                                  description: Help text that will appear in the UI
                                  default: A streamlined, end-to-end technology for employers, employees and individuals to sponsor, shop and enroll in insurance benefits
                              namespaces:
                                - key: :features
                                  namespaces:
                                    - key: :aca_shop_market
                                      settings:
                                        - key: is_required
                                          description: Feature must be enabled if true
                                          default: false
                                        - key: is_enabled
                                          description: Feature must be enabled if true
                                          default: false
                                        - key: alt_key
                                          description: Shortened Key reference to be used in Registry
                                          default: shop
                                        - key: :title
                                          description: Name for this setting that will appear in the UI
                                          default: ACA SHOP Market
                                        - key: :description
                                          description: Help text that will appear in the UI
                                          default: ACA Small Business Health Options (SHOP) Portal
                                      namespaces:
                                        - key: :options
                                          namespaces:
                                            - key: :settings
                                              settings:
                                                - key: small_market_employee_count_maximumt
                                                  type: :integer
                                                  default: 50
                                                - key: employer_contribution_percent_minimum
                                                  type: :integer
                                                  default: 50
                                        - key: :features                                          
                                    - key: :aca_individual_market
                                      settings:
                                        - key: is_required
                                          description: Feature must be enabled if true
                                          default: false
                                        - key: is_enabled
                                          description: Feature must be enabled if true
                                          default: false
                                        - key: alt_key
                                          description: Shortened Key reference to be used in Registry
                                          default: ivl
                                        - key: :title
                                          description: Name for this setting that will appear in the UI
                                          default: ACA Individual Market
                        - key: :options
                          namespaces:
                            - key: :settings
                              settings:
                                - key: copyright_period_start
                                  type: :string
                                  default: "2013"
                                - key: policies_url
                                  type: :string
                                  default: "https://dchealthlink.com/"         
                                - key: faqs_url
                                  type: :string
                                  default: "https://www.dchealthlink.com/Frequently-Asked-Questions"   
                                - key: help_url
                                  type: :string
                                  default: "https://www.dchealthlink.com/help"  
                                - key: business_resource_center_url
                                  type: :string
                                  default: "https://dchealthlink.com/smallbusiness/"    
                                - key: nondiscrimination_notice_url
                                  type: :string
                                  default: "https://www.dchealthlink.com/nondiscrimination"