# This yaml describes our current checks.
#   Any checks marked "# TODO: RWC" are "re-enable when corrected.RWC" are "re-enable when corrected.

# We will add the following back in later, but they cause
#   a completely outsized amount of cop failures for the number of files:
# - db/seedfiles
# - lib/tasks
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - "./bin/**/*"
    - "./project_gems/effective_datatables-2.6.14/effective_datatables-2.6.14.gemspec"
    - "./node_modules/**/*"
    - "./db/seedfiles/**/*"
    - "./lib/tasks/**/*"
    - "./script/**/*"
    - "./components/benefit_markets/spec/dummy/**/*"
    - "./components/benefit_markets/db/seedfiles/**/*"
    - "./components/benefit_sponsors/spec/dummy/**/*"
    - "./components/benefit_sponsors/db/seedfiles/**/*"
    - "./components/notifier/spec/dummy/**/*"
    - "./components/old_sponsored_benefits/**/*"
    - "./components/sponsored_benefits/spec/dummy/**/*"
    - "./components/transport_profiles/spec/dummy/**/*"
    - "./components/transport_profiles/spec/dummy/**/*"
    - "./eyes/enroll.eye.rb"

# TODO: RWC
Layout/CommentIndentation:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

# Re-enable once other problems are solved
Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/IndentationWidth:
  Enabled: true

Layout/LineLength:
  Max: 250

Layout/IndentationStyle:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Metrics/AbcSize:
  Max: 50

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 15

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/AndOr:
  Enabled: true

Style/BlockComments:
  Enabled: false

# We will want to turn this back on or customize it more fully
Style/Documentation:
  Enabled: true

Style/EachWithObject:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/NumericPredicate:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/WordArray:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled:
    false

Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: true
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true
Lint/DeprecatedConstants: # (new in 1.8)
  Enabled: true
Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: true
Lint/EmptyClass: # (new in 1.3)
  Enabled: true
Lint/LambdaWithoutLiteralBlock: # (new in 1.8)
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true
Lint/RedundantDirGlobSort: # (new in 1.8)
  Enabled: true
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true
Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true
Style/CollectionCompact: # (new in 1.2)
  Enabled: true
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true
Style/EndlessMethod: # (new in 1.8)
  Enabled: true
Style/HashExcept: # (new in 1.7)
  Enabled: true
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true
Style/NilLambda: # (new in 1.3)
  Enabled: true
Style/RedundantArgument: # (new in 1.4)
  Enabled: true
Style/SwapValues: # (new in 1.1)
  Enabled: true

require:
  - ./cops/lint/empty_rescue_clause.rb
# Deprecated
# Style/TrailingBlankLines:
#   Enabled: false
# AllCops:
#   RunRailsCops: true
