# This yaml describes our current checks.
#   Any checks marked "# TODO: RWC" are "re-enable when corrected.RWC" are "re-enable when corrected.

# We will add the following back in later, but they cause
#   a completely outsized amount of cop failures for the number of files:
# - db/seedfiles
# - lib/tasks
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - "./bin/**/*"
    - "./project_gems/effective_datatables-2.6.14/effective_datatables-2.6.14.gemspec"
    - "./node_modules/**/*"
    - "./db/seedfiles/**/*"
    - "./lib/tasks/**/*"
    - "./script/**/*"
    - "./components/benefit_markets/spec/dummy/**/*"
    - "./components/benefit_markets/db/seedfiles/**/*"
    - "./components/benefit_sponsors/spec/dummy/**/*"
    - "./components/benefit_sponsors/db/seedfiles/**/*"
    - "./components/notifier/spec/dummy/**/*"
    - "./components/old_sponsored_benefits/**/*"
    - "./components/sponsored_benefits/spec/dummy/**/*"
    - "./components/transport_profiles/spec/dummy/**/*"
    - "./components/transport_profiles/spec/dummy/**/*"
    - "./eyes/enroll.eye.rb"

# TODO: RWC
Layout/CommentIndentation:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

# Re-enable once other problems are solved
Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/IndentationWidth:
  Enabled: true

Layout/LineLength:
  Max: 250

Layout/Tab:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Metrics/AbcSize:
  Max: 50

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 15

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/AndOr:
  Enabled: true

Style/BlockComments:
  Enabled: false

# We will want to turn this back on or customize it more fully
Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/NumericPredicate:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/WordArray:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled:
    false

require:
  - ./cops/lint/empty_rescue_clause.rb
# Deprecated
# Style/TrailingBlankLines:
#   Enabled: false
# AllCops:
#   RunRailsCops: true
