# This yaml describes our current checks.
#   Any checks marked "# TODO: RWC" are "re-enable when corrected.RWC" are "re-enable when corrected.

# We will add the following back in later, but they cause
#   a completely outsized amount of cop failures for the number of files:
# - db/seedfiles
# - lib/tasks
I18n/RailsI18n:
  Enabled: true
I18n/GetText:
  Enabled: false
I18n/GetText/DecorateString:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6.6

require:
  - rubocop-i18n
