version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      RAILS_ENV: development
      DB_HOST: db
    entrypoint: ./entrypoints/docker-entrypoint.sh
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mongo:4.2
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/db_config
    ports:
      - 27017:27017

volumes:
  mongodb:
  mongodb_config:
