production:
  clients:
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: <%= ENV['ENROLL_DB_NAME'] %>
      hosts:
        - <%= ENV['ENROLL_DB_HOST'] %>:<%= ENV['ENROLL_DB_PORT'] %>
      options:
      <% if ENV['ENROLL_DB_AUTH'] %>
        replica_set: <%= ENV['ENROLL_DB_REPLICA_SET_NAME'] %>

        user: <%= ENV['ENROLL_DB_USERNAME'] %>
        password: <%= ENV['ENROLL_DB_PASSWORD'] %>
        auth_source: admin

        write:
          w: 1
          j: true
      <% end %>
      # Change whether the session persists in safe mode by default.
      # (default: false)
      # safe: false

      # Change the default consistency model to :eventual or :strong.
      # :eventual will send reads to secondaries, :strong sends everything
      # to master. (default: :eventual)
      # consistency: :eventual

      # How many times Moped should attempt to retry an operation after
      # failure. (default: 30)
      # max_retries: 30

      # The time in seconds that Moped should wait before retrying an
      # operation on failure. (default: 1)
      # retry_interval: 1
      # Configure Mongoid specific options. (optional)
  options:

