
USER_MAILER_TRANSLATIONS = {
  "en.user_mailer.generic_consumer.bottom_text" => "<p>Questions? Call %{contact_center_name} at %{contact_center_phone_number}, or go online to <a href=%{site_home_business_url}>%{site_short_name}<a/></p><p>%{site_short_name} is strongly committed to maintaining the privacy of your personal information and the security of our computer systems. With respect to the collection, use and disclosure of personal information, %{site_short_name} makes every effort to ensure compliance with applicable Federal law.</p>",
  "en.user_mailer.generic_notice_alert.full_text" => "<p>Dear %{first_name} </p>,<br/><p>You have a new message from %{site_short_name} about your health coverage that may be time sensitive and require action. Please log in to your account at <a href=%{site_home_business_url}>%{site_short_name}<a/> to read this message.<br><br/>Questions?</p><p>Call %{site_short_name} Customer Service at %{contact_center_phone_number}, or go to <a href=%{site_home_business_url}>%{site_short_name}<a/>.<br/><br/><p><i>%{site_short_name} is strongly committed to maintaining the privacy of your personal information and the security of our computer systems. With respect to the collection, use and disclosure of personal information, %{site_short_name} makes every effort to ensure compliance with applicable Federal law.</i></p>",
  "en.user_mailer.broker_staff_invitation_email.full_text" => "<html><body>%{person_name},<br /><div>Thank you for registering as a broker staff through %{site_short_name}.</div><div>Please visit <a href='%{invitation_url}' target='_blank'>%{invitation_url}</a> to create your broker staff account and manage your clients.</div></body></html>",
  "en.user_mailer.broker_pending_missing_training_completed_carrier.full_text" => "Dear %{applicant_name},<br/><br/>We regret to inform you that your broker application has been denied. For more details, Please call %{contact_center_name} at %{contact_center_phone_number}.<br/><br/>%{site_short_name} is strongly committed to maintaining the privacy of your personal information and the security of our computer systems. With respect to the collection, use and disclosure of personal information, %{site_short_name} makes every effort to ensure compliance with applicable Federal law.",
  "en.user_mailer.broker_invitation_email.partial_text" => "<html><body>%{person_name}<br/><div>Thank you for registering as a broker through %{site_short_name}.</div><div></div></body></html>",
  "en.user_mailer.broker_invitation_email.full_text" => "<html><body><div>Dear %{person_name},</div><br/><div>Congratulations-- we've reviewed your application and you are now approved as a certified broker through %{site_short_name} for Business.</div><div><p><strong>Next Steps:</strong></p></div><div><p><strong>1.</strong> Click on this personalized link to set up your new broker account: <a href='%{claim_invitation_url(invitation)}' target='_blank'> %{site_short_name}</a> <br/><strong>Important:</strong> You must use this link to set up your account. If you don't use your personalized link when creating your account, the account won't be connected to your existing broker profile.</p></div><div><p><strong>2.</strong> After you've set up your new username and password, log in to your new %{site_short_name} for Business broker account through <a href='%{site_user_sign_in_url}' target='_blank'>our website</a>.</p></div><div><p>If you have questions or need help, please call us at %{contact_center_phone_number} (TTY: %{contact_center_tty_number}).</p></div><div><p> Thank you, </p> <br /> <p> %{site_title} </p></div>",
  "en.user_mailer.broker_application_confirmation.full_text" => "<html><body><div>Dear %{person},</div><br/><div>Thank you for submitting your broker application to %{site_short_name}. Please allow 7-10 business days for %{site_short_name} to review your application.</div><br/><div>If there are any unsatisfied requirements you will receive an email notification detailing any outstanding requirements that must be satisfied before your application can be approved. Upon approval of your registration, you will receive an email from %{site_noreply_email_address} with important information about how to access your broker portal and how your clients can assign you as their broker.</div><br/><div>Brokers need to fulfill the following requirements as detailed in the broker registration guide: <ul><li>%{site_short_name} Broker training course (worth 4 C.E. credits)</li><li>Carrier Requirements: Appointments by all health insurance carrier licensed entity for the market in which you intend to sell</li><li>DC resident or non-resident health insurance producer license that is active and in good standing</li></ul></div><br/><div>More information about these requirements is included in the <a href='%{site_broker_registration_guide}'> Broker Registration Guide </a></div><br/><div>Please reach out to %{site_short_name} at %{site_producer_email_address} with any questions.</div></body></html>",
  "en.user_mailer.broker_invitation.broker_app_submission" => "<html><body><div>Dear %{person},</div><br/><div>Thank you for submitting your application to become a certified broker through %{site_short_name} for Business. We'll review your application to make sure that you meet all of the requirements for our certified brokers.</div><br/><div><strong>You should expect to receive another email from us about your next steps within 7-10 business days.</strong></div><br/><div>If you meet all of our requirements for certified brokers, your next email will include information on how to access the broker portal, including creating a username and password.</div><br/><div>If you do not appear to meet all of our requirements, we will let you know which steps you will need to take before you can become a %{site_short_name}-certified broker.</div><br/><div>If you have questions, please visit the <a href='%{certification_url}'>broker certification section of our website</a>, or call us at %{contact_center_phone_number} (TTY: %{contact_center_tty_number}).</div><br/><div>Thank you,</div><br/><div>%{site_title}</div><br/></body></html>",
  "en.user_mailer.broker_invitation.message_to_broker" => "<html><body>Hello %{broker_name},<br/>You received message from %{person_name} with help regarding plan shopping page.<br/>Here is the information requested:><br/>%{message_body}</body></html>"
}
