---
registry:
  - namespace:
    - :enroll_app
    - :aca_individual_market
    features:
      - key: :residency_self_attestation
        item: :residency_attestation
        is_enabled: true
        settings:
          - key: :effective_period
            item: <%= Date.new(2020,6,6)..Date.new(2021,5,20) %>
      - key: :verification_sensitive_attributes
        item: :consumer_role_hub_call
        is_enabled: true
        settings:
          - key: :demographic_attributes
            item: ['first_name', 'last_name', 'ssn', 'us_citizen', 'naturalized_citizen', 'eligible_immigration_status', 'dob']
      - key: :special_enrollment_period
        is_enabled: true
        settings:
          - key: :individual_market_monthly_enrollment_due_on
            item: 20
          - key: :fifteenth_of_the_month
            item: 15
      - key: :aca_individual_assistance_benefits
        is_enabled: true
        settings:
          - key: :default_applied_aptc_percentage
            item: 0.85
      - key: :cancel_renewals_for_term
        item: Operations::Individual::CancelRenewalEnrollment.new
        is_enabled: true
      - key: :calculate_monthly_aggregate
        item: Operations::Individual::CalculateMonthlyAggregate.new
        is_enabled: true
        settings:
          - key: :termination_date
            item: :end_of_month
          - key: :eligible_months
            item: true
      - key: :apply_aggregate_to_enrollment
        item: Operations::Individual::ApplyAggregateToEnrollment.new
        is_enabled: true
      - key: :vlp_documents
        is_enabled: true
        settings:
          - key: :vlp_document_kind_options
            item: [ "I-327 (Reentry Permit)", "I-551 (Permanent Resident Card)", "I-571 (Refugee Travel Document)", "I-766 (Employment Authorization Card)",
                    "Certificate of Citizenship","Naturalization Certificate","Machine Readable Immigrant Visa (with Temporary I-551 Language)", "Temporary I-551 Stamp (on passport or I-94)", "I-94 (Arrival/Departure Record)",
                    "I-94 (Arrival/Departure Record) in Unexpired Foreign Passport", "Unexpired Foreign Passport",
                    "I-20 (Certificate of Eligibility for Nonimmigrant (F-1) Student Status)", "DS2019 (Certificate of Eligibility for Exchange Visitor (J-1) Status)",
                    "Other (With Alien Number)", "Other (With I-94 Number)" ]
      - key: :indian_alaskan_tribe_details
        is_enabled: false
      - key: :prior_plan_year_ivl_sep
        is_enabled: :false
      - key: :admin_ivl_end_date_changes
        is_enabled: :false
      - key: :display_external_id_in_family_datatable
        is_enabled: :false
      - key: :contact_method_via_dropdown
        is_enabled: :true
      - key: :state_based_language_preferences
        item: ["English", "Amharic", "Spanish"]
        is_enabled: true
      - key: :extended_aptc_individual_agreement_message
        item: :extended_aptc_individual_agreement_message
        is_enabled: false
