---
registry:
  - namespace:
    - :enroll_app
    - :aca_individual_market
    - :enrollment_renewals
    features:
      - key: :generate_initial_enrollment_on_subscriber_drop
        item: :generate_initial_enrollment_on_subscriber_drop
        is_enabled: <%= ENV['GENERATE_INITIAL_ENROLLMENT_ON_SUBSCRIBER_DROP_IS_ENABLED'] || false %>
