site:
  key: :dc
  subdomain: "dchbx"
  domain_name: "dchealthlink.com"
  site_title: "DC's Online Health Insurance Marketplace"
  home_url: "https://www.dchealthlink.com/"
  home_business_url: "https://www.dchealthlink.com/smallbusiness/overview"
  # copyright_period_start: "2013"
  # help_url: "https://www.dchealthlink.com/help"
  # faqs_url: "https://www.dchealthlink.com/Frequently-Asked-Questions"
  # business_resource_center_url: "https://dchealthlink.com/smallbusiness/"
  # nondiscrimination_notice_url: "https://www.dchealthlink.com/nondiscrimination"
  # policies_url: "https://dchealthlink.com/"
  main_web_address_url: "https://www.dchealthlink.com/"
  invoice_bill_url: "https://www.e-billexpress.com/ebpp/DCHEALTHPAY/"
  payment_pdf_url: "pdf/employers_paying_your_premiums_online.pdf"
  user_sign_in_url: "https://www.dchealthlink.com/"
  website_name: "www.DCHealthLink.com"
  main_web_address: "www.DCHealthLink.com"
  health_care_website: "www.healthcare.gov"
  health_care_website_url: "https://www.healthcare.gov"
  short_name: "DC Health Link"
  byline: "Welcome to the District's Health Insurance Marketplace"
  long_name: "District of Columbia Health Link"
  header_message: "Welcome to the District's Health Insurance Marketplace"
  logo_file_name: "logo.png"
  make_their_premium_payments_online: "https://www.e-billexpress.com/ebpp/DCHEALTHPAY/"
  tab_icon: 'favicon.ico'
  mailer_logo_file_name: "dchealthlink.jpg"
  employer_application_deadline_link: "https://dchealthlink.com/smallbusiness/employer-coverage-deadlines"
  s3_prefix: "dchbx"
  broker_quoting_enabled: false
  broker_claim_quoting_enabled: true
  guidance_for_business_owners_url: "https://dchealthlink.com/sites/default/files/v2/forms/Guidance_for_Business_Owners.pdf"
  use_default_devise_path: true
  plan_options_title_for_ma: true
  create_routes: ['/insured/employee/privacy','/employers/employer_profiles/new', '/insured/consumer_role/privacy']
  sign_in_routes: ['/families/home']
  shop_find_your_doctor_url: "https://dc.checkbookhealth.org/dc/"
  document_verification_checklist_url: "https://www.mahealthconnector.org/business/business-resource-center/employer-verification-checklist"
  terms_and_conditions_url: "https://www.dchealthlink.com/terms"
  certification_url: "https://www.dchealthlink.com/brokers/overview"
  registration_path: "https://www.dchealthlink.com/smallbusiness"
  home_forms_url: "https://dchealthlink.com/forms"
  forms_name: "DCHealthLink.com/forms"
  short_url: "dchealthlink.com"
  forms: "https://dchealthlink.com/forms#en"
  website_url: "www.healthcare.gov"
  healthcare_name: "www.healthcare.gov"
  healthcare_url: "https://www.healthcare.gov/"
  irs_url: "https://www.irs.gov/"
  exchange_hbx_id: "DC0"
  mail_address: "info@dchealthlink.com"
  privacy_policy: "https://dchealthlink.com/"
  late_rates_message: "Due to a delay, premiums for some coverage effective dates are not available yet. Please check again soon to see if this information has been updated. You can also contact Customer Service or your broker if you need help."
  faa_enabled: false # TODO: Remove this after configuring the settings.
  ivl_responsibility_url: "https://dchealthlink.com/individual-responsibility-requirement"

  exchange_name: "Washington DC Health Benefit Exchange"
  social_media:
    facebook_url: ""

contact_center:
  name: "DC Health Link's Customer Care Center"
  alt_name: "DC Health Link Customer Service"
  po_box: "PO Box 97022"
  phone_number: "1-855-532-5465"
  fax: "1-617-933-3099"
  alt_fax: "617-722-4033"
  tty_number: "711"
  short_number: "(855) 532-5465"
  tty: "771"
  alt_phone_number: "1-855-532-LINK"
  payment_phone_number: "855-532-LINK"
  ivl_number: "1-877-623-6765"
  ivl_phone_number: "1-877-623-6765"
  email_address: "info@dchealthlink.com"
  po_box: "PO Box 97022"
  city: "Washington"
  state: "DC"
  zip_code: "20090"
  small_business_email: "info@dchealthlink.com"
  non_discrimination_email: "info@dchealthlink.com"

  appeals: "info@dchealthlink.com"

  mailing_address:
    name: "DC Health Link"
    address_1: "PO Box 97022"
    address_2:
    city: "Washington"
    state: "DC"
    zip_code: "20090"

  appeal_center:
    name: "DC Health Link"
    address_1: "PO Box 97022"
    address_2:
    city: "Washington"
    state: "DC"
    zip_code: "20090"

  non_discrimination:
    email: "info@dchealthlink.com"
    phone_1: "1-855-532-5465"
    phone_2: "1-855-532-5465"
    phone_3: "1-855-532-5465"
    complaint_url: "https://www.hhs.gov/civil-rights/filing-a-complaint"

plan_option_titles:
  sole_source: 'One Plan'
  metal_level: 'By Metal Level'
  single_carrier: 'By Carrier'
  single_plan: 'Single Plan'
  plan_year_tooltip: "Employer premium contribution for Employee Only Health Plans must be at least"
  multi_product: 'Custom'
  single_issuer: 'By Carrier'

plan_option_descriptions:
  sole_source: "Choose one plan and your contribution amount. All employees can enroll in that plan."
  metal_level: "Select your preferred metal level. Your plan participants will be able to choose any plan by any carrier within the metal level you select. Your costs will be fixed to a specific plan you’ll choose in a minute. Bronze means the plan is expected to pay 60% of expenses for an average population of consumers, Silver 70%, Gold 80% and Platinum 90%."
  single_carrier: "Select your preferred insurance company carrier. Your plan participants will be able to choose any plan offered by the carrier you select. Your costs will be fixed to a specific plan you’ll choose in a minute."
  single_plan: "Select your preferred insurance company carrier. You will then select one plan and it'll be the only plan your participants can choose. It'll never cost you more to let your plan participants choose by carrier or by metal level. Are you sure you only want to offer a single plan?"
  dental:
    single_plan: "For Dental coverage, you will choose one dental plan from one carrier as the option that all of your employees can enroll in."
    single_issuer: "Select your preferred insurance company carrier. Your plan participants will be able to choose any plan offered by the carrier you select. Your costs will be fixed to a specific plan you’ll choose in a minute."
    multi_product: "Select your preferred insurance company carrier. Your plan participants will be able to choose any plan offered by the carrier you select. Your costs will be fixed to a specific plan you’ll choose in a minute."

invoices:
  addendum: 'ma_non_discrimination_and_language_tags.pdf'
  minimum_invoice_display_year: 2015

aca:
  state_key : "dc"
  state_name: "District of Columbia"
  state_abbreviation: "DC"
  market_kinds: ["shop", "individual", "fehb"]

  hbx_abbreviation: "DC Health Benefit Exchange"
  nationwide_markets: true
  general_agency_enabled: true
  broker_carrier_appointments_enabled: true
  dental_market_enabled: true
  calendar_enabled: true
  dental_plan_years_available: [""]
  minimum_primary_contribution_percentage: 50
  minimum_family_contribution_percentage: 30
  address_query_county: false
  broker_routing_information: false
  recaptcha_enabled: false
  security_questions: false
  user_accounts_enabled: true
  plan_options_available: ["single_plan", "single_carrier", "metal_level"]
  dental_plan_options_available: ["multi_product", "single_issuer"]
  default_dental_option_kind: 'multi_product'
  ## acceptable options are ["sole_source", "single_carrier", "metal_level", "single_plan"]
  enabled_metal_levels_for_single_carrier: ["bronze", "silver", "gold", "platinum", "dental"]
  carrier_hios_logo_variant:
    '': ""
  ## acceptable options are ["platinum", "gold", "silver", "dental"]

  plan_option_years:
    single_carriers_available: ['2018', '2019']
    sole_source_carriers_available: ['2017','2018', '2019']
    metal_level_carriers_available: ['2018', '2019']

  qle:
    with_in_sixty_days: 60
  #
  individual_market:
    monthly_enrollment_due_on: 18
    verification_outstanding_window:
      days: 0
    verification_due:
      days: 95

    open_enrollment:
      start_on: <%= Date.new(2019,11,1) %>
      end_on: <%= Date.new(2020,01,31) %>
    dc_resident_application: true
    transition_family_members_link: true
      # dc_resident_application: true
      # transition_family_members_link: true
    upcoming_open_enrollment:
      start_on: <%= Date.new(2019,11,1) %>
      end_on: <%= Date.new(2020,01,31) %>

  shop_market:
    valid_employer_attestation_documents_url: 'https://www.mahealthconnector.org/business/business-resource-center/employer-verification-checklist'
    small_market_employee_count_maximum: 50
    employer_contribution_percent_minimum: 50
    employer_dental_contribution_percent_minimum: 0
    employer_family_contribution_percent_minimum: 0
    employee_participation_ratio_minimum: <%= 2 / 3.0 %>
    non_owner_participation_count_minimum: 1
    binder_payment_due_on: 12
    small_market_active_employee_limit: 200
    new_employee_paper_application: true
    census_employees_template_file: 'DCHL Employee Census'
    coverage_start_period: "2 months"
    auto_cancel_ineligible: false

    employee:
      default_contact_method: 'Only Electronic communications'

    binder_payment_dates: [
      {"2019-01-01": '2018,12,12'},
      {"2019-02-01": '2019,1,14'},
      {"2019-03-01": '2019,2,12'},
      {"2019-04-01": '2019,3,12'},
      {"2019-05-01": '2019,4,12'},
      {"2019-06-01": '2019,5,14'},
      {"2019-07-01": '2019,6,12'},
      {"2019-08-01": '2019,7,12'},
      {"2019-09-01": '2019,8,13'},
      {"2019-10-01": '2019,9,12'},
      {"2019-11-01": '2019,10,15'},
      {"2019-12-01": '2019,11,13'},
      {"2020-01-01": '2019,12,13'},
      {"2020-02-01": '2020,1,14'},
      {"2020-03-01": '2020,2,12'},
      {"2020-04-01": '2020,3,12'},
      {"2020-05-01": '2020,4,14'},
      {"2020-06-01": '2020,5,12'},
      {"2020-07-01": '2020,6,12'},
      {"2020-08-01": '2020,7,14'},
      {"2020-09-01": '2020,8,12'},
      {"2020-10-01": '2020,9,14'},
      {"2020-11-01": '2020,10,14'},
      {"2020-12-01": '2020,11,13'},
    ]

    earliest_enroll_prior_to_effective_on:
      days: -30
    latest_enroll_after_effective_on:
      days: 30
    latest_enroll_after_employee_roster_correction_on:
      days: 30

    retroactive_coverage_termination_maximum:
      days: -60

    initial_application:
      publish_due_day_of_month: 5
      advertised_deadline_of_month: 1
      non_binder_paid_notice_day_of_month: 16
      earliest_start_prior_to_effective_on:
        months: -3
        day_of_month: 0
      appeal_period_after_application_denial:
        days: 30
      # After submitting an ineligible plan year application, time period an Employer must wait
      ineligible_period_after_application_denial:
        days: 90
      quiet_period:
        month_offset: -1
        mday: 28

    renewal_application:
      earliest_start_prior_to_effective_on:
        months: -3
        day_of_month: 0
      monthly_open_enrollment_end_on: 13
      publish_due_day_of_month: 10
      application_submission_soft_deadline: 5
      force_publish_day_of_month: 11
      open_enrollment:
        minimum_length:
          days: 3
      quiet_period:
        month_offset: -1
        mday: 15

    benefit_period:
      length_minimum:
        year: 1
      length_maximum:
        year: 1

    open_enrollment:
      monthly_start_on: 1
      monthly_end_on: 10

      minimum_length:
        days: 5
        adv_days: 10
      maximum_length:
        months: 2

    cobra_enrollment_period:
      months: 6

    group_file:
      new_enrollment_transmit_on: 16
      update_transmit_day_of_week: "friday"

    broker_agency_profile:
      minimum_commission_statement_year: 2017

    transmit_scheduled_employers: true
    employer_transmission_day_of_month: 16
    transmit_carrier_drop_events: true

    mid_month_benefit_application_terminations:
      voluntary: false
      non_payment: true
      show_termination_reasons: false

  transmit_employers_immediately: false
  employer_has_sic_field: false
  employer_registration_has_referred_by_field: false
  validate_county: false

  use_simple_employer_calculation_model: true
  carrier_special_plan_identifier_namespace: "urn:MA:terms:v1:plan:super_group_id#"
  offerings_constrained_to_service_areas: false
  employer_attestation: false
  enforce_employer_attestation: false
  plan_match_tool: true

  rating_areas:
    - R-DC001

notices:
  individual_market:
    mail_address:
      address_1: "PO Box 44018"
      city: "Washington"
      zip_code: "20026"

  shop_market:
    mail_address:
      address_1: "1225 I Street, NW"
      address_2: "Suite 400"
      zip_code: "20005"

  shop:
    store_paper_notice: false
    attachments:
      envelope_without_address: "taglines.pdf"
      non_discrimination_attachment: "shop_non_discrimination_attachment.pdf"
      employee_appeal_rights: "employee_appeal_rights.pdf"
    partials:
      template: "notifier/notice_kinds/template.html.erb"
      header: "notices/shared/shop_header.html.erb"
      footer: "notices/shared/shop_footer.html.erb"
      layout: "notifier/pdf_layout.html.erb"

  individual:
    store_paper_notice: true
    attachments:
      blank_page_attachment: "blank.pdf"
      envelope_without_address: "taglines.pdf"
      non_discrimination_attachment: "ivl_non_discrimination.pdf"
      voter_application: "voter_application.pdf"
    partials:
      template: "notifier/notice_kinds/ivl_template.html.erb"
      header: "notices/shared/header_ivl.html.erb"
      footer: "notices/shared/footer_ivl.html.erb"
      layout: "notifier/ivl_pdf_layout.html.erb"

paper_notice: 'paper-notices'
# Note: Remote Aceess keys ad URL's Provided by DC checkbook
checkbook_services:
# Note: Need to replace Remote_access_key with Production keys while deploying to prod.
    remote_access_key: 'cd535a89-49ea-4ea6-862f-e9558e8bef50'
    reference_id: "9F03A78ADF324AFDBFBEF8E838770132"
    base_url:  "https://staging.checkbookhealth.org"
    url: "https://staging.checkbookhealth.org"
    congress_url: "https://dc.checkbookhealth.org/congress/dc/2018/"
    plan_match: "DC"
    current_year: 2019
    previous_year: 2018

aptc_errors:
  effective_date_overflow: "Updates not allowed at this time. Effective Date happens to be after the Policy's life (next year) when following the 15th day rule."
  enrollment_max_smaller_than_applied: "Max Applied APTC for any Enrollment cannot be smaller than the Applied APTC."
  plan_premium_smaller_than_applied: "Applied APTC for any Enrollment cannot be greater than the Plan Premium."
  max_aptc_non_numeric: "Max APTC needs to be a numeric value."
  max_aptc_too_small: "Max APTC should be greater than or equal to the sum of APTC Applied for all enrollments."
  max_aptc_too_big: "Max APTC should be less than 9999.99"

#   ShopOpenEnrollmentBeginDueDayOfMonth = ShopOpenEnrollmentEndDueDayOfMonth - ShopOpenEnrollmentPeriodMinimum
#   ShopPlanYearPublishedDueDayOfMonth = ShopOpenEnrollmentBeginDueDayOfMonth

style:
  primary_orange: '#333333'
  brand_primary: '#007bc4'
  primary_color:  '#007bc4'
  primary_notification: '#333333'
  primary_panel: '#69A30D'
  primary_button: '#e72b2d'
  primary_button_color: '#286090'
  primary_button_disabled: '#337ab7'
  primary_button_border_disabled: '#2e6da4'
  alternate_header_color: '#333333'
  primary_icon_color: '#333333'
  qle_header_color: '#333333'
  primary_header_font: "'Open Sans', serif"
