source 'https://rubygems.org'

# Declare your gem's dependencies in benefit_sponsors.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]

gem "notifier", path: "../notifier"
gem "benefit_markets", path: "../benefit_markets"
gem "sponsored_benefits", path: "../sponsored_benefits"
gem "effective_datatables", path: ".../../../../project_gems/effective_datatables-2.6.14"
