# require File.expand_path(File.join(File.dirname(__FILE__), "translations_seed"))
# require File.expand_path(File.join(File.dirname(__FILE__), "cca", "qles_seed"))
require File.expand_path(File.join(File.dirname(__FILE__), "cca", "benefit_markets_seed"))
require File.expand_path(File.join(File.dirname(__FILE__), "cca", "locations_seed"))
require File.expand_path(File.join(File.dirname(__FILE__), "cca", "factors_seed"))
require File.expand_path(File.join(File.dirname(__FILE__), "cca", "products_seed"))
require File.expand_path(File.join(File.dirname(__FILE__), "cca", "pricing_and_contribution_models_seed"))
require File.expand_path(File.join(File.dirname(__FILE__), "cca", "ma_benefit_market_catalogs_product_packages"))
require File.expand_path(File.join(File.dirname(__FILE__),  "data_migrations_seed"))
