# require File.expand_path(File.join(File.dirname(__FILE__), "..", "translations_seed"))
require File.expand_path(File.join(File.dirname(__FILE__), "cca", "site_seed"))
require File.expand_path(File.join(File.dirname(__FILE__), "cca", "issuer_profiles_seed"))
require File.expand_path(File.join(File.dirname(__FILE__), "cca", "employer_profiles_seed"))
require File.expand_path(File.join(File.dirname(__FILE__), "data_migrations_seed"))
