
source 'https://rubygems.org'

# Declare your gem's dependencies in sponsored_benefits.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

gem "benefit_markets", path: "../benefit_markets"
gem 'benefit_sponsors', path: '../benefit_sponsors'
gem "effective_datatables", path: ".../../../../project_gems/effective_datatables-2.6.14"
gem 'aca_entities',       git: 'https://github.com/dchbx/aca_entities.git', branch: 'trunk'
gem 'webpacker', '~> 4.0.2'
gem 'resource_registry',  git:  'https://github.com/ideacrew/resource_registry.git', branch: 'trunk'

# To use a debugger
# gem 'byebug', group: [:development, :test]

group :development, :test do
  gem 'rails-controller-testing', '~> 1.0', '>= 1.0.5'
end
