---
registry:
  - namespace:
      - :enroll_app
  features:
    - key: :preaudit_reports
      item: :preaudit_reports
      is_enabled: false
      settings:
        - key: :report_creation_day
          item: 17
