source 'https://rubygems.org'

# Declare your gem's dependencies in transport_profiles.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gem "transport_gateway", path: File.expand_path("../../transport_gateway", __FILE__)
gem 'acapi',   git: "https://github.com/ideacrew/acapi.git", branch: 'master'
gem 'mongoid', git: 'https://github.com/mongodb/mongoid.git', ref: 'df6b2168ee7526f0c5e26f64f38851b91a0623e8'

gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]

