# frozen_string_literal: true

source 'https://rubygems.org'

# Declare your gem's dependencies in financial_assistance.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]

gem 'resource_registry',  git: 'https://github.com/ideacrew/resource_registry.git', branch: 'trunk'
gem 'acapi',              git: 'https://github.com/ideacrew/acapi.git', branch: 'trunk'
gem 'aca_entities',       git: 'https://github.com/ideacrew/aca_entities.git', branch: 'test_mongoid_fields_issue'
gem 'event_source',       git:  'https://github.com/ideacrew/event_source.git', branch: 'trunk'
gem 'ui_helpers', path: '../ui_helpers'

group :development, :test do
  gem 'rails-controller-testing'
  gem 'nokogiri-happymapper', :require => 'happymapper'
end
