---
registry:
  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :benefit_market_catalog
    - :catalog_2025
    features:
      - key: :aca_shop_fetch_enrollment_minimum_participation_2025
        item: BenefitMarkets::Operations::BenefitSponsorCatalogs::FetchMinimumParticipation.new
        is_enabled: false
        settings:
          - key: :zero_percent_sponsor_fixed_percent_contribution_model
            item: 0
          - key: :fifty_percent_sponsor_fixed_percent_contribution_model
            item: <%= 2 / 3.0 %>
      - key: :fehb_fetch_enrollment_minimum_participation_2025
        item: BenefitMarkets::Operations::BenefitSponsorCatalogs::FetchMinimumParticipation.new
        is_enabled: false
        settings:
          - key: :zero_percent_sponsor_fixed_percent_contribution_model
            item: 0
          - key: :fifty_percent_sponsor_fixed_percent_contribution_model
            item: <%= 2 / 3.0 %>  
  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :benefit_market_catalog
    - :catalog_2025
    - :contribution_model_criteria
    features:
      - key: :initial_sponsor_jan_default_2025
        item: :contribution_model_criterion
        is_enabled: false
        settings:
          - key: :contribution_model_key
            item: :zero_percent_sponsor_fixed_percent_contribution_model
          - key: :benefit_application_kind
            item: :initial
          - key: :effective_period
            item: <%= Date.new(2025,1,1)..Date.new(2025,1,31) %>
          - key: :order
            item: 1
          - key: :default
            item: false
          - key: :renewal_criterion_key
            item: :initial_sponsor_jan_default
      - key: :initial_sponsor_default_2025
        item: :contribution_model_criterion
        is_enabled: false
        settings:
          - key: :contribution_model_key
            item: :zero_percent_sponsor_fixed_percent_contribution_model
          - key: :benefit_application_kind
            item: :initial
          - key: :effective_period
            item: <%= Date.new(2025,2,1)..Date.new(2025,12,31) %>
          - key: :order
            item: 3
          - key: :default
            item: true
          - key: :renewal_criterion_key
            item: :initial_sponsor_default
      - key: :renewal_sponsor_jan_default_2025
        item: :contribution_model_criterion
        is_enabled: false
        settings:
          - key: :contribution_model_key
            item: :zero_percent_sponsor_fixed_percent_contribution_model
          - key: :benefit_application_kind
            item: :renewal
          - key: :effective_period
            item: <%= Date.new(2025,1,1)..Date.new(2025,1,31) %>
          - key: :order
            item: 4
          - key: :default
            item: false
          - key: :renewal_criterion_key
            item: :renewal_sponsor_jan_default
      - key: :renewal_sponsor_default_2025
        item: :contribution_model_criterion
        is_enabled: false
        settings:
          - key: :contribution_model_key
            item: :zero_percent_sponsor_fixed_percent_contribution_model
          - key: :benefit_application_kind
            item: :renewal
          - key: :effective_period
            item: <%= Date.new(2025,2,1)..Date.new(2025,12,31) %>
          - key: :order
            item: 2
          - key: :default
            item: true
          - key: :renewal_criterion_key
            item: :renewal_sponsor_default
