development:
  # Configure available database sessions. (required)
  clients:
    # Defines the default session. (required)
    default: &default
      database: <%= ENV['DB_DATABASE'] %>
      hosts:
        - <%= ENV['DB_HOST'] %>:<%= ENV['DB_PORT'] %>
      options:
        # Change the default write concern. (default = { w: 1 })
        # write:
        # w: 1
  options:
test:
  clients:
    default:
      <<: *default
      database: enroll_test<%= ENV['TEST_ENV_NUMBER'] %>
      options:
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 2
        retry_interval: 0
production:
  clients:
    default:
      <<: *default
      options:
        replica_set: <%= ENV['DB_REPLICA_SET'] %>

        user: <%= ENV['DB_USERNAME'] %>
        password: <%= ENV['DB_PASSWORD'] %>
        auth_source: <%= ENV['DB_AUTH_SOURCE'] %>

        #write:
        #  w: 1
        #  j: true

