---
registry:
  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :benefit_market_catalog
    - :catalog_2024
    features:
      - key: :aca_shop_fetch_enrollment_minimum_participation_2024
        item: BenefitMarkets::Operations::BenefitSponsorCatalogs::FetchMinimumParticipation.new
        is_enabled: false
        settings:
          - key: :zero_percent_sponsor_fixed_percent_contribution_model
            item: 0
          - key: :fifty_percent_sponsor_fixed_percent_contribution_model
            item: <%= 2 / 3.0 %>
      - key: :fehb_fetch_enrollment_minimum_participation_2024
        item: BenefitMarkets::Operations::BenefitSponsorCatalogs::FetchMinimumParticipation.new
        is_enabled: false
        settings:
          - key: :zero_percent_sponsor_fixed_percent_contribution_model
            item: 0
          - key: :fifty_percent_sponsor_fixed_percent_contribution_model
            item: <%= 2 / 3.0 %>  
  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :benefit_market_catalog
    - :catalog_2024
    - :contribution_model_criteria
    features:
      - key: :initial_sponsor_jan_default_2024
        item: :contribution_model_criterion
        is_enabled: false
        settings:
          - key: :contribution_model_key
            item: :zero_percent_sponsor_fixed_percent_contribution_model
          - key: :benefit_application_kind
            item: :initial
          - key: :effective_period
            item: <%= Date.new(2024,1,1)..Date.new(2024,1,31) %>
          - key: :order
            item: 1
          - key: :default
            item: false
          - key: :renewal_criterion_key
            item: :initial_sponsor_jan_default
      - key: :initial_sponsor_default_2024
        item: :contribution_model_criterion
        is_enabled: false
        settings:
          - key: :contribution_model_key
            item: :zero_percent_sponsor_fixed_percent_contribution_model
          - key: :benefit_application_kind
            item: :initial
          - key: :effective_period
            item: <%= Date.new(2024,2,1)..Date.new(2024,12,31) %>
          - key: :order
            item: 3
          - key: :default
            item: true
          - key: :renewal_criterion_key
            item: :initial_sponsor_default
      - key: :renewal_sponsor_jan_default_2024
        item: :contribution_model_criterion
        is_enabled: false
        settings:
          - key: :contribution_model_key
            item: :zero_percent_sponsor_fixed_percent_contribution_model
          - key: :benefit_application_kind
            item: :renewal
          - key: :effective_period
            item: <%= Date.new(2024,1,1)..Date.new(2024,1,31) %>
          - key: :order
            item: 4
          - key: :default
            item: false
          - key: :renewal_criterion_key
            item: :renewal_sponsor_jan_default
      - key: :renewal_sponsor_default_2024
        item: :contribution_model_criterion
        is_enabled: false
        settings:
          - key: :contribution_model_key
            item: :zero_percent_sponsor_fixed_percent_contribution_model
          - key: :benefit_application_kind
            item: :renewal
          - key: :effective_period
            item: <%= Date.new(2024,2,1)..Date.new(2024,12,31) %>
          - key: :order
            item: 2
          - key: :default
            item: true
          - key: :renewal_criterion_key
            item: :renewal_sponsor_default
  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :benefit_market_catalog
    - :catalog_2024
    - :osse_eligibility_criteria
    features:
      - key: :aca_shop_benefit_sponsorship_osse_subsidy_2024
        item: :osse_eligibility_criterion
        is_enabled: false
        settings:
        - key: :grants_offered
          item:
            - :minimum_participation_rule_relaxed_2024
            - :all_contribution_levels_min_met_relaxed_2024
            - :benefit_application_fte_count_relaxed_2024
            - :employer_metal_level_products_restricted_2024
      - key: :minimum_participation_rule_relaxed_2024
        item: minimum_participation_rule
        is_enabled: false
      - key: :all_contribution_levels_min_met_relaxed_2024
        item: 'all_contribution_levels_min_met'
        is_enabled: false
      - key: :benefit_application_fte_count_relaxed_2024
        item: 'benefit_application_fte_count'
        is_enabled: false
      - key: :employer_metal_level_products_restricted_2024
        item: 'employer_metal_level_products'
        is_enabled: false
      - key: :aca_shop_employee_role_osse_subsidy_2024
        item: :osse_eligibility_criterion
        is_enabled: false
        settings:
        - key: :grants_offered
          item:
            - :osse_subsidy_2024
      - key: :osse_subsidy_2024
        item: osse_subsidy_2024
        is_enabled: false
      - key: :aca_shop_osse_subsidy_2024
        item: :aca_shop_osse_subsidy_2024
        is_enabled: <%= ENV['SHOP_OSSE_ELIGIBILITY_2024_IS_ENABLED'] || false %>
      - key: :lowest_cost_silver_product_2024
        item: '94506DC0350033-01'
        is_enabled: <%= ENV['SHOP_OSSE_ELIGIBILITY_2024_IS_ENABLED'] || false %>