# frozen_string_literal: true


# key value pairs of all maine towns/cities and counties

# Source Code for getting these values:
# Add mechanize to gem file
# This source code didn't include the cities listed in the first table here (I.E. Bangor, etc.) those were added manually
# agent = Mechanize.new
# agent.log = Logger.new "mech.log"
# agent.user_agent_alias = 'Mac Safari'
# agent.verify_mode = OpenSSL::SSL::VERIFY_NONE
# page = agent.get('https://en.wikipedia.org/wiki/List_of_municipalities_in_Maine')
# doc = Nokogiri::HTML(page.body)
# cities_and_counties_tables =  doc.css('table').select { |table| table[:class] == "sortable wikitable" }.map(&:to_s).flatten.pop
# sanitized_array = ActionView::Base.full_sanitizer.sanitize(cities_and_counties_tables).split("\n").reject { |value| value == "" || !value[/\d/].nil? || ["Town", "County", "Land area(sq mil)"].include?(value) }
# county_and_city_names = sanitized_array
# counties = county_and_city_names.find_all { |county_or_city_name| county_and_city_names.count(county_or_city_name) > 1 }.uniq
# hash_of_counties_and_cities = Hash[counties.map { |county_name| [county_name, []] }]
# county_and_city_names.each do |county_or_city_name|
  # Is a county
  # next if county_and_city_names.count(county_or_city_name) > 1
  # position of city/town in array
  # position_of_town = county_and_city_names.index(county_or_city_name)
  # county_name = county_and_city_names[position_of_town + 1]
  # puts("County name for #{county_or_city_name} is #{county_name}")
  # hash_of_counties_and_cities[county_name] << county_or_city_name
# end
# hash_of_counties_and_cities
# https://en.wikipedia.org/wiki/List_of_municipalities_in_Maine
# rubocop:disable Metrics/ModuleLength
module MeCountyHelper
  # rubocop:disable Metrics/MethodLength
  def maine_counties_and_towns
    {
      "Cumberland" =>
        [
          "Westbrook",
          "South Portland",
          "Brunswick",
          "Scarborough",
          "Windham",
          "Gorham",
          "Falmouth",
          "Standish",
          "Cape Elizabeth",
          "Yarmouth",
          "Freeport",
          "Gray",
          "New Gloucester",
          "Bridgton",
          "Harpswell",
          "Raymond",
          "Naples",
          "Casco",
          "North Yarmouth",
          "Harrison",
          "Sebago",
          "Baldwin",
          "Pownal",
          "Chebeague Island",
          "Long Island",
          "Frye Island",
          "Portland"
       ],
      "York" =>
        [
          "York",
          "Biddeford",
          "Sanford",
          "Saco",
          "Kennebunk",
          "Wells",
          "Kittery",
          "Old Orchard Beach",
          "Buxton",
          "Waterboro",
          "Berwick",
          "South Berwick",
          "Eliot",
          "Lebanon",
          "North Berwick",
          "Hollis",
          "Lyman",
          "Arundel",
          "Limington",
          "Kennebunkport",
          "Alfred",
          "Limerick",
          "Shapleigh",
          "Acton",
          "Dayton",
          "Parsonsfield",
          "Newfield",
          "Cornish",
          "Ogunquit"
],
      "Penobscot" =>
    ["Old Town",
     "Brewer",
     "Bangor",
     "Orono",
     "Hampden",
     "Hermon",
     "Glenburn",
     "Millinocket",
     "Dexter",
     "Orrington",
     "Newport",
     "Holden",
     "Milford",
     "Levant",
     "Corinth",
     "Carmel",
     "Eddington",
     "Corinna",
     "Veazie",
     "East Millinocket",
     "Enfield",
     "Hudson",
     "Newburgh",
     "Greenbush",
     "Bradley",
     "Charleston",
     "Plymouth",
     "Kenduskeag",
     "Medway",
     "Bradford",
     "Etna",
     "Howland",
     "Stetson",
     "Dixmont",
     "Garland",
     "Exeter",
     "Patten",
     "Clifton",
     "Lee",
     "Alton",
     "Lagrange",
     "Mattawamkeag",
     "Chester",
     "Springfield",
     "Burlington",
     "Winn",
     "Stacyville",
     "Lowell",
     "Passadumkeag",
     "Woodville",
     "Mount Chase",
     "Edinburg",
     "Lakeville",
     "Maxfield"],
      "Androscoggin" =>
 [
  "Auburn",
  "Lisbon",
  "Turner",
  "Poland",
  "Sabattus",
  "Greene",
  "Durham",
  "Livermore Falls",
  "Mechanic Falls",
  "Minot",
  "Leeds",
  "Livermore",
  "Wales",
  "Lewiston"
 ],
      "Sagadahoc" =>
  ["Bath",
   "Topsham",
   "Richmond",
   "Bowdoin",
   "Woolwich",
   "Bowdoinham",
   "Phippsburg",
   "West Bath",
   "Georgetown",
   "Arrowsic"],
      "Somerset" =>
  ["Skowhegan",
   "Fairfield",
   "Madison",
   "Pittsfield",
   "Norridgewock",
   "Anson",
   "Canaan",
   "St. Albans",
   "Palmyra",
   "Hartland",
   "Cornville",
   "Solon",
   "Athens",
   "Smithfield",
   "Embden",
   "Harmony",
   "Bingham",
   "Jackman",
   "Detroit",
   "New Portland",
   "Mercer",
   "Starks",
   "Moscow",
   "Ripley",
   "Cambridge",
   "Moose River",
   "Caratunk"],
      "Kennebec" =>
  ["Hallowell",
   "Gardiner",
   "Augusta",
   "Waterville",
   "Winslow",
   "Oakland",
   "Winthrop",
   "Vassalboro",
   "China",
   "Sidney",
   "Monmouth",
   "Litchfield",
   "West Gardiner",
   "Clinton",
   "Belgrade",
   "Farmingdale",
   "Chelsea",
   "Benton",
   "Pittston",
   "Windsor",
   "Manchester",
   "Readfield",
   "Albion",
   "Randolph",
   "Mount Vernon",
   "Wayne",
   "Fayette",
   "Rome",
   "Vienna"],
      "Franklin" =>
  ["Farmington",
   "Jay",
   "Wilton",
   "New Sharon",
   "Chesterville",
   "Strong",
   "Rangeley",
   "Phillips",
   "Kingfield",
   "Industry",
   "New Vineyard",
   "Carrabassett Valley",
   "Eustis",
   "Carthage",
   "Temple",
   "Avon",
   "Weld"],
      "Aroostook" =>
  ["Caribou",
   "Presque Isle",
   "Houlton",
   "Fort Kent",
   "Madawaska",
   "Fort Fairfield",
   "Limestone",
   "Van Buren",
   "Mapleton",
   "Washburn",
   "Mars Hill",
   "Hodgdon",
   "Ashland",
   "Easton",
   "Woodland",
   "Frenchville",
   "Littleton",
   "Linneus",
   "Eagle Lake",
   "Island Falls",
   "Sherman",
   "Monticello",
   "St. Agatha",
   "Oakfield",
   "Blaine",
   "New Sweden",
   "Bridgewater",
   "Wallagrass",
   "Westfield",
   "New Limerick",
   "St. Francis",
   "Chapman",
   "Grand Isle",
   "Smyrna",
   "Castle Hill",
   "Ludlow",
   "Portage Lake",
   "Perham",
   "New Canada",
   "Caswell",
   "Wade",
   "Merrill",
   "Crystal",
   "Stockholm",
   "Masardis",
   "Amity",
   "Allagash",
   "Weston",
   "Hamlin",
   "Dyer Brook",
   "Orient",
   "Haynesville",
   "Hammond",
   "Hersey",
   "Westmanland"],
      "Oxford" =>
  ["Rumford",
   "Paris",
   "Norway",
   "Fryeburg",
   "Bethel",
   "Mexico",
   "Dixfield",
   "Buckfield",
   "West Paris",
   "Otisfield",
   "Brownfield",
   "Hiram",
   "Waterford",
   "Peru",
   "Porter",
   "Hebron",
   "Woodstock",
   "Hartford",
   "Denmark",
   "Lovell",
   "Canton",
   "Sumner",
   "Greenwood",
   "Andover",
   "Stow",
   "Sweden",
   "Roxbury",
   "Newry",
   "Hanover",
   "Stoneham",
   "Gilead",
   "Byron",
   "Upton"],
      "Hancock" =>
  ["Ellsworth",
   "Bar Harbor",
   "Bucksport",
   "Blue Hill",
   "Orland",
   "Mount Desert",
   "Deer Isle",
   "Southwest Harbor",
   "Gouldsboro",
   "Dedham",
   "Lamoine",
   "Tremont",
   "Trenton",
   "Surry",
   "Castine",
   "Sullivan",
   "Sedgwick",
   "Stonington",
   "Brooksville",
   "Brooklin",
   "Otis",
   "Verona Island",
   "Mariaville",
   "Winter Harbor",
   "Eastbrook",
   "Waltham",
   "Swan's Island",
   "Sorrento",
   "Amherst",
   "Cranberry Isles",
   "Aurora",
   "Osborn",
   "Frenchboro",
   "Great Pond"],
      "Lincoln" =>
  ["Waldoboro",
   "Wiscasset",
   "Boothbay",
   "Bristol",
   "Jefferson",
   "Whitefield",
   "Damariscotta",
   "Boothbay Harbor",
   "Newcastle",
   "Dresden",
   "Nobleboro",
   "Edgecomb",
   "South Bristol",
   "Bremen",
   "Westport Island",
   "Alna",
   "Southport",
   "Somerville"],
      "Knox" =>
  ["Rockland",
   "Camden",
   "Warren",
   "Rockport",
   "Thomaston",
   "St. George",
   "Union",
   "Hope",
   "South Thomaston",
   "Owls Head",
   "Cushing",
   "Appleton",
   "Vinalhaven",
   "Friendship",
   "North Haven",
   "Isle au Haut"],
      "Piscataquis" =>
  ["Dover-Foxcroft",
   "Milo",
   "Greenville",
   "Guilford",
   "Sangerville",
   "Brownville",
   "Parkman",
   "Abbot",
   "Monson",
   "Sebec",
   "Medford",
   "Wellington",
   "Shirley",
   "Willimantic",
   "Beaver Cove",
   "Bowerbank"],
      "Waldo" =>
  ["Belfast",
   "Winterport",
   "Searsport",
   "Lincolnville",
   "Unity",
   "Stockton Springs",
   "Northport",
   "Palermo",
   "Searsmont",
   "Swanville",
   "Burnham",
   "Frankfort",
   "Brooks",
   "Montville",
   "Troy",
   "Liberty",
   "Belmont",
   "Monroe",
   "Thorndike",
   "Morrill",
   "Freedom",
   "Prospect",
   "Islesboro",
   "Jackson"],
      "Washington" =>
  ["Easport",
   "Calais",
   "Machias",
   "Baileyville",
   "Jonesport",
   "East Machias",
   "Lubec",
   "Milbridge",
   "Addison",
   "Cherryfield",
   "Steuben",
   "Machiasport",
   "Harrington",
   "Perry",
   "Pembroke",
   "Princeton",
   "Danforth",
   "Jonesboro",
   "Robbinston",
   "Columbia Falls",
   "Marshfield",
   "Beals",
   "Cutler",
   "Alexander",
   "Whiting",
   "Columbia",
   "Dennysville",
   "Charlotte",
   "Roque Bluffs",
   "Topsfield",
   "Whitneyville",
   "Meddybemps",
   "Cooper",
   "Northfield",
   "Vanceboro",
   "Crawford",
   "Waite",
   "Wesley",
   "Talmadge",
   "Deblois",
   "Beddington",
   "Lambert Lake"]
    }
  end

  def maine_towns_county_and_geocode
    {
      'Abbot' => {:county => "Piscataquis", :geocode => "11001"},
      'Acton' => {:county => "York", :geocode => "16001"},
      'Addison' => {:county => "Washington", :geocode => "15001"},
      'Albany Twp' => {:county => "Oxford", :geocode => "09001"},
      'Albion' => {:county => "Kennebec", :geocode => "06001"},
      'Alder Stream Twp' => {:county => "Franklin", :geocode => "04032"},
      'Alexander' => {:county => "Washington", :geocode => "15002"},
      'Alfred' => {:county => "York", :geocode => "16002"},
      'Allagash' => {:county => "Aroostook", :geocode => "02002"},
      'Alna' => {:county => "Lincoln", :geocode => "08001"},
      'Alton' => {:county => "Penobscot", :geocode => "10002"},
      'Amherst' => {:county => "Hancock", :geocode => "05001"},
      'Amity' => {:county => "Aroostook", :geocode => "02003"},
      'Andover' => {:county => "Oxford", :geocode => "09002"},
      'Andover North Surplus' => {:county => "Oxford", :geocode => "09003"},
      'Andover West Surplus Twp' => {:county => "Oxford", :geocode => "09004"},
      'Anson' => {:county => "Somerset", :geocode => "13001"},
      'Appleton' => {:county => "Knox", :geocode => "07001"},
      'Ar 2 Twp' => {:county => "Aroostook", :geocode => "02001"},
      'Ar 7 Twp' => {:county => "Penobscot", :geocode => "10001"},
      'Argyle Twp' => {:county => "Penobscot", :geocode => "10003"},
      'Arrowsic' => {:county => "Sagadahoc", :geocode => "12001"},
      'Arundel' => {:county => "York", :geocode => "16019"},
      'Ashland' => {:county => "Aroostook", :geocode => "02004"},
      'Athens' => {:county => "Somerset", :geocode => "13002"},
      'Atkinson' => {:county => "Piscataquis", :geocode => "11002"},
      'Auburn' => {:county => "Androscoggin", :geocode => "01001"},
      'Augusta' => {:county => "Kennebec", :geocode => "06002"},
      'Aurora' => {:county => "Hancock", :geocode => "05002"},
      'Avon' => {:county => "Franklin", :geocode => "04001"},
      'Baileyville' => {:county => "Washington", :geocode => "15003"},
      'Bald Mountain Twp T2 R3' => {:county => "Somerset", :geocode => "13003"},
      'Baldwin' => {:county => "Cumberland", :geocode => "03001"},
      'Bancroft' => {:county => "Aroostook", :geocode => "02005"},
      'Bangor' => {:county => "Penobscot", :geocode => "10004"},
      'Bar Harbor' => {:county => "Hancock", :geocode => "05003"},
      'Baring Plt' => {:county => "Washington", :geocode => "15004"},
      'Barnard Twp' => {:county => "Piscataquis", :geocode => "11003"},
      'Bath' => {:county => "Sagadahoc", :geocode => "12002"},
      'Beals' => {:county => "Washington", :geocode => "15005"},
      'Beddington' => {:county => "Washington", :geocode => "15006"},
      'Belfast' => {:county => "Waldo", :geocode => "14001"},
      'Belgrade' => {:county => "Kennebec", :geocode => "06003"},
      'Belmont' => {:county => "Waldo", :geocode => "14002"},
      'Benedicta Twp' => {:county => "Aroostook", :geocode => "02006"},
      'Benton' => {:county => "Kennebec", :geocode => "06004"},
      'Berwick' => {:county => "York", :geocode => "16003"},
      'Bethel' => {:county => "Oxford", :geocode => "09005"},
      'Biddeford' => {:county => "York", :geocode => "16004"},
      'Big Squaw Mt Twp' => {:county => "Piscataquis", :geocode => "11026"},
      'Bigelow Twp' => {:county => "Somerset", :geocode => "13004"},
      'Bingham' => {:county => "Somerset", :geocode => "13005"},
      'Blaine' => {:county => "Aroostook", :geocode => "02007"},
      'Blanchard Twp' => {:county => "Piscataquis", :geocode => "11004"},
      'Blue Hill' => {:county => "Hancock", :geocode => "05004"},
      'Boothbay' => {:county => "Lincoln", :geocode => "08002"},
      'Boothbay Harbor' => {:county => "Lincoln", :geocode => "08003"},
      'Bowdoin' => {:county => "Sagadahoc", :geocode => "12003"},
      'Bowdoinham' => {:county => "Sagadahoc", :geocode => "12004"},
      'Bowerbank' => {:county => "Piscataquis", :geocode => "11005"},
      'Bradford' => {:county => "Penobscot", :geocode => "10005"},
      'Bradley' => {:county => "Penobscot", :geocode => "10006"},
      'Bremen' => {:county => "Lincoln", :geocode => "08004"},
      'Brewer' => {:county => "Penobscot", :geocode => "10007"},
      'Bridgewater' => {:county => "Aroostook", :geocode => "02008"},
      'Bridgton' => {:county => "Cumberland", :geocode => "03002"},
      'Brighton Plt' => {:county => "Somerset", :geocode => "13006"},
      'Bristol' => {:county => "Lincoln", :geocode => "08005"},
      'Brooklin' => {:county => "Hancock", :geocode => "05005"},
      'Brooks' => {:county => "Waldo", :geocode => "14003"},
      'Brooksville' => {:county => "Hancock", :geocode => "05006"},
      'Brookton Twp' => {:county => "Washington", :geocode => "15007"},
      'Brownfield' => {:county => "Oxford", :geocode => "09006"},
      'Brownville' => {:county => "Piscataquis", :geocode => "11006"},
      'Brunswick' => {:county => "Cumberland", :geocode => "03003"},
      'Buckfield' => {:county => "Oxford", :geocode => "09007"},
      'Bucksport' => {:county => "Hancock", :geocode => "05007"},
      'Burlington' => {:county => "Penobscot", :geocode => "10008"},
      'Burnham' => {:county => "Waldo", :geocode => "14004"},
      'Buxton' => {:county => "York", :geocode => "16005"},
      'Byron' => {:county => "Oxford", :geocode => "09008"},
      'C Surplus' => {:county => "Oxford", :geocode => "09011"},
      'C Twp' => {:county => "Oxford", :geocode => "09009"},
      'Calais' => {:county => "Washington", :geocode => "15008"},
      'Cambridge' => {:county => "Somerset", :geocode => "13007"},
      'Camden' => {:county => "Knox", :geocode => "07002"},
      'Canaan' => {:county => "Somerset", :geocode => "13008"},
      'Canton' => {:county => "Oxford", :geocode => "09010"},
      'Cape Elizabeth' => {:county => "Cumberland", :geocode => "03004"},
      'Caratunk' => {:county => "Somerset", :geocode => "13009"},
      'Caribou' => {:county => "Aroostook", :geocode => "02009"},
      'Carmel' => {:county => "Penobscot", :geocode => "10009"},
      'Carrabassett Valley' => {:county => "Franklin", :geocode => "04012"},
      'Carroll Plt' => {:county => "Penobscot", :geocode => "10010"},
      'Carrying Place Twp' => {:county => "Somerset", :geocode => "13010"},
      'Carthage' => {:county => "Franklin", :geocode => "04002"},
      'Cary Plt' => {:county => "Aroostook", :geocode => "02010"},
      'Casco' => {:county => "Cumberland", :geocode => "03005"},
      'Castine' => {:county => "Hancock", :geocode => "05008"},
      'Castle Hill' => {:county => "Aroostook", :geocode => "02011"},
      'Caswell' => {:county => "Aroostook", :geocode => "02012"},
      'Centerville Twp' => {:county => "Washington", :geocode => "15009"},
      'Chain Of Ponds Twp' => {:county => "Franklin", :geocode => "04033"},
      'Chapman' => {:county => "Aroostook", :geocode => "02013"},
      'Charleston' => {:county => "Penobscot", :geocode => "10011"},
      'Charlotte' => {:county => "Washington", :geocode => "15010"},
      'Chelsea' => {:county => "Kennebec", :geocode => "06005"},
      'Cherryfield' => {:county => "Washington", :geocode => "15011"},
      'Chester' => {:county => "Penobscot", :geocode => "10012"},
      'Chesterville' => {:county => "Franklin", :geocode => "04003"},
      'Chesuncook Twp' => {:county => "Piscataquis", :geocode => "11007"},
      'China' => {:county => "Kennebec", :geocode => "06006"},
      'Clifton' => {:county => "Penobscot", :geocode => "10013"},
      'Clinton' => {:county => "Kennebec", :geocode => "06007"},
      'Coburn Gore' => {:county => "Franklin", :geocode => "04034"},
      'Codyville Plt' => {:county => "Washington", :geocode => "15012"},
      'Columbia' => {:county => "Washington", :geocode => "15013"},
      'Columbia Falls' => {:county => "Washington", :geocode => "15014"},
      'Concord Twp' => {:county => "Somerset", :geocode => "13011"},
      'Connor Twp' => {:county => "Aroostook", :geocode => "02014"},
      'Cooper' => {:county => "Washington", :geocode => "15015"},
      'Coplin Plt' => {:county => "Franklin", :geocode => "04004"},
      'Corinna' => {:county => "Penobscot", :geocode => "10014"},
      'Corinth' => {:county => "Penobscot", :geocode => "10015"},
      'Cornish' => {:county => "York", :geocode => "16006"},
      'Cornville' => {:county => "Somerset", :geocode => "13012"},
      'Cranberry Isles' => {:county => "Hancock", :geocode => "05009"},
      'Crawford' => {:county => "Washington", :geocode => "15016"},
      'Criehaven Twp' => {:county => "Knox", :geocode => "07019"},
      'Crockertown Twp' => {:county => "Franklin", :geocode => "04005"},
      'Crystal' => {:county => "Aroostook", :geocode => "02015"},
      'Cty Tn Unk' => {:county => "County Unknown", :geocode => "99999"},
      'Cumberland' => {:county => "Cumberland", :geocode => "03006"},
      'Cushing' => {:county => "Knox", :geocode => "07003"},
      'Cutler' => {:county => "Washington", :geocode => "15017"},
      'Cyr Plt' => {:county => "Aroostook", :geocode => "02016"},
      'Dallas Plt' => {:county => "Franklin", :geocode => "04006"},
      'Damariscotta' => {:county => "Lincoln", :geocode => "08006"},
      'Danforth' => {:county => "Washington", :geocode => "15018"},
      'Dayton' => {:county => "York", :geocode => "16007"},
      'Dead River Twp' => {:county => "Somerset", :geocode => "13013"},
      'Deblois' => {:county => "Washington", :geocode => "15019"},
      'Dedham' => {:county => "Hancock", :geocode => "05010"},
      'Deer Isle' => {:county => "Hancock", :geocode => "05011"},
      'Denmark' => {:county => "Oxford", :geocode => "09012"},
      'Dennistown Plt' => {:county => "Somerset", :geocode => "13014"},
      'Dennysville' => {:county => "Washington", :geocode => "15020"},
      'Detroit' => {:county => "Somerset", :geocode => "13015"},
      'Dexter' => {:county => "Penobscot", :geocode => "10016"},
      'Dixfield' => {:county => "Oxford", :geocode => "09013"},
      'Dixmont' => {:county => "Penobscot", :geocode => "10017"},
      'Dover-Foxcroft' => {:county => "Piscataquis", :geocode => "11008"},
      'Dresden' => {:county => "Lincoln", :geocode => "08007"},
      'Drew Plt' => {:county => "Penobscot", :geocode => "10018"},
      'Durham' => {:county => "Androscoggin", :geocode => "01002"},
      'Dyer Brook' => {:county => "Aroostook", :geocode => "02017"},
      'E Twp' => {:county => "Aroostook", :geocode => "02018"},
      'Eagle Lake' => {:county => "Aroostook", :geocode => "02019"},
      'East Central Penobscot' => {:county => "Penobscot", :geocode => "10079"},
      'East Machias' => {:county => "Washington", :geocode => "15021"},
      'East Millinocket' => {:county => "Penobscot", :geocode => "10019"},
      'Eastbrook' => {:county => "Hancock", :geocode => "05012"},
      'Easton' => {:county => "Aroostook", :geocode => "02020"},
      'Eastport' => {:county => "Washington", :geocode => "15022"},
      'Eddington' => {:county => "Penobscot", :geocode => "10020"},
      'Edgecomb' => {:county => "Lincoln", :geocode => "08008"},
      'Edinburg' => {:county => "Penobscot", :geocode => "10021"},
      'Edmunds Twp' => {:county => "Washington", :geocode => "15023"},
      'Eliot' => {:county => "York", :geocode => "16008"},
      'Elliottsville Twp' => {:county => "Piscataquis", :geocode => "11009"},
      'Ellsworth' => {:county => "Hancock", :geocode => "05013"},
      'Embden' => {:county => "Somerset", :geocode => "13016"},
      'Enfield' => {:county => "Penobscot", :geocode => "10022"},
      'Etna' => {:county => "Penobscot", :geocode => "10023"},
      'Eustis' => {:county => "Franklin", :geocode => "04007"},
      'Exeter' => {:county => "Penobscot", :geocode => "10024"},
      'Fairfield' => {:county => "Somerset", :geocode => "13017"},
      'Falmouth' => {:county => "Cumberland", :geocode => "03007"},
      'Farmingdale' => {:county => "Kennebec", :geocode => "06008"},
      'Farmington' => {:county => "Franklin", :geocode => "04008"},
      'Fayette' => {:county => "Kennebec", :geocode => "06009"},
      'Forest City Twp' => {:county => "Washington", :geocode => "15024"},
      'Forkstown Twp' => {:county => "Aroostook", :geocode => "02021"},
      'Fort Fairfield' => {:county => "Aroostook", :geocode => "02022"},
      'Fort Kent' => {:county => "Aroostook", :geocode => "02023"},
      'Frankfort' => {:county => "Waldo", :geocode => "14005"},
      'Franklin' => {:county => "Hancock", :geocode => "05014"},
      'Freedom' => {:county => "Waldo", :geocode => "14006"},
      'Freeman Twp' => {:county => "Franklin", :geocode => "04009"},
      'Freeport' => {:county => "Cumberland", :geocode => "03008"},
      'Frenchboro' => {:county => "Hancock", :geocode => "05018"},
      'Frenchtown Twp' => {:county => "Piscataquis", :geocode => "11031"},
      'Frenchville' => {:county => "Aroostook", :geocode => "02024"},
      'Friendship' => {:county => "Knox", :geocode => "07004"},
      'Fryeburg' => {:county => "Oxford", :geocode => "09014"},
      'Gardiner' => {:county => "Kennebec", :geocode => "06010"},
      'Garfield Plt' => {:county => "Aroostook", :geocode => "02025"},
      'Garland' => {:county => "Penobscot", :geocode => "10025"},
      'Georgetown' => {:county => "Sagadahoc", :geocode => "12005"},
      'Gilead' => {:county => "Oxford", :geocode => "09015"},
      'Glenburn' => {:county => "Penobscot", :geocode => "10026"},
      'Glenwood Plt' => {:county => "Aroostook", :geocode => "02026"},
      'Gorham' => {:county => "Cumberland", :geocode => "03009"},
      'Gouldsboro' => {:county => "Hancock", :geocode => "05015"},
      'Grafton Twp' => {:county => "Oxford", :geocode => "09016"},
      'Grand Falls Twp' => {:county => "Penobscot", :geocode => "10027"},
      'Grand Isle' => {:county => "Aroostook", :geocode => "02027"},
      'Grand Lake Stream Plt' => {:county => "Washington", :geocode => "15025"},
      'Gray' => {:county => "Cumberland", :geocode => "03010"},
      'Greenbush' => {:county => "Penobscot", :geocode => "10028"},
      'Greene' => {:county => "Androscoggin", :geocode => "01003"},
      'Greenfield Twp' => {:county => "Penobscot", :geocode => "10029"},
      'Greenville' => {:county => "Piscataquis", :geocode => "11010"},
      'Greenwood' => {:county => "Oxford", :geocode => "09017"},
      'Guilford' => {:county => "Piscataquis", :geocode => "11011"},
      'Hallowell' => {:county => "Kennebec", :geocode => "06011"},
      'Hamlin ' => {:county => "Aroostook", :geocode => "02028"},
      'Hammond Plt' => {:county => "Aroostook", :geocode => "02029"},
      'Hampden' => {:county => "Penobscot", :geocode => "10030"},
      'Hancock' => {:county => "Hancock", :geocode => "05016"},
      'Hanover' => {:county => "Oxford", :geocode => "09018"},
      'Harmony' => {:county => "Somerset", :geocode => "13019"},
      'Harpswell' => {:county => "Cumberland", :geocode => "03011"},
      'Harrington' => {:county => "Washington", :geocode => "15026"},
      'Harrison' => {:county => "Cumberland", :geocode => "03012"},
      'Hartford' => {:county => "Oxford", :geocode => "09019"},
      'Hartfords Point Twp' => {:county => "Piscataquis", :geocode => "11039"},
      'Hartland' => {:county => "Somerset", :geocode => "13020"},
      'Haynesville' => {:county => "Aroostook", :geocode => "02030"},
      'Hebron' => {:county => "Oxford", :geocode => "09020"},
      'Hermon' => {:county => "Penobscot", :geocode => "10031"},
      'Hersey' => {:county => "Aroostook", :geocode => "02031"},
      'Highland Plt' => {:county => "Somerset", :geocode => "13021"},
      'Hiram' => {:county => "Oxford", :geocode => "09021"},
      'Hodgdon' => {:county => "Aroostook", :geocode => "02032"},
      'Holden' => {:county => "Penobscot", :geocode => "10032"},
      'Hollis' => {:county => "York", :geocode => "16009"},
      'Hope' => {:county => "Knox", :geocode => "07005"},
      'Houlton' => {:county => "Aroostook", :geocode => "02033"},
      'Howland' => {:county => "Penobscot", :geocode => "10033"},
      'Hudson' => {:county => "Penobscot", :geocode => "10034"},
      'Hurricane Isle' => {:county => "Knox", :geocode => "07020"},
      'Indian Isl Res' => {:county => "Penobscot", :geocode => "10081"},
      'Indian Purchase 3 Twp' => {:county => "Penobscot", :geocode => "10073"},
      'Indian Purchase 4 Twp' => {:county => "Penobscot", :geocode => "10075"},
      'Industry' => {:county => "Franklin", :geocode => "04010"},
      'Island Falls' => {:county => "Aroostook", :geocode => "02034"},
      'Isle au Haut' => {:county => "Knox", :geocode => "07006"},
      'Islesboro' => {:county => "Waldo", :geocode => "14007"},
      'Jackman' => {:county => "Somerset", :geocode => "13022"},
      'Jackson' => {:county => "Waldo", :geocode => "14008"},
      'Jay' => {:county => "Franklin", :geocode => "04011"},
      'Jefferson' => {:county => "Lincoln", :geocode => "08009"},
      'Jim Pond Twp' => {:county => "Franklin", :geocode => "04035"},
      'Johnson Mountain Twp' => {:county => "Somerset", :geocode => "13023"},
      'Jonesboro' => {:county => "Washington", :geocode => "15027"},
      'Jonesport' => {:county => "Washington", :geocode => "15028"},
      'Katahdin Iron Works Twp' => {:county => "Piscataquis", :geocode => "11050"},
      'Kenduskeag' => {:county => "Penobscot", :geocode => "10035"},
      'Kennebunk' => {:county => "York", :geocode => "16010"},
      'Kennebunkport' => {:county => "York", :geocode => "16011"},
      'Kineo Twp' => {:county => "Piscataquis", :geocode => "11029"},
      'Kingfield' => {:county => "Franklin", :geocode => "04013"},
      'Kingman Twp' => {:county => "Penobscot", :geocode => "10036"},
      'Kingsbury Plt' => {:county => "Piscataquis", :geocode => "11012"},
      'Kittery' => {:county => "York", :geocode => "16012"},
      'Knox' => {:county => "Waldo", :geocode => "14009"},
      'Kossuth Twp' => {:county => "Washington", :geocode => "15029"},
      'Lagrange' => {:county => "Penobscot", :geocode => "10037"},
      'Lake View Plt' => {:county => "Piscataquis", :geocode => "11013"},
      'Lakeville' => {:county => "Penobscot", :geocode => "10038"},
      'Lambert Lake Twp' => {:county => "Washington", :geocode => "15030"},
      'Lamoine' => {:county => "Hancock", :geocode => "05017"},
      'Lang Twp' => {:county => "Franklin", :geocode => "04014"},
      'Lebanon' => {:county => "York", :geocode => "16013"},
      'Lee' => {:county => "Penobscot", :geocode => "10039"},
      'Leeds' => {:county => "Androscoggin", :geocode => "01004"},
      'Levant' => {:county => "Penobscot", :geocode => "10040"},
      'Lewiston' => {:county => "Androscoggin", :geocode => "01005"},
      'Lexington Twp' => {:county => "Somerset", :geocode => "13024"},
      'Liberty' => {:county => "Waldo", :geocode => "14010"},
      'Lily Bay Twp' => {:county => "Piscataquis", :geocode => "11014"},
      'Limerick' => {:county => "York", :geocode => "16014"},
      'Limestone' => {:county => "Aroostook", :geocode => "02035"},
      'Limington' => {:county => "York", :geocode => "16015"},
      'Lincoln' => {:county => "Penobscot", :geocode => "10041"},
      'Lincoln Plt' => {:county => "Oxford", :geocode => "09022"},
      'Lincolnville' => {:county => "Waldo", :geocode => "14011"},
      'Linneus' => {:county => "Aroostook", :geocode => "02036"},
      'Lisbon Falls' => {:county => "Androscoggin", :geocode => "01006"},
      'Litchfield' => {:county => "Kennebec", :geocode => "06012"},
      'Little Squaw Mt Twp' => {:county => "Piscataquis", :geocode => "11027"},
      'Littleton' => {:county => "Aroostook", :geocode => "02037"},
      'Livermore' => {:county => "Androscoggin", :geocode => "01007"},
      'Livermore Falls' => {:county => "Androscoggin", :geocode => "01008"},
      'Long Island' => {:county => "Cumberland", :geocode => "03028"},
      'Long Pond Twp' => {:county => "Somerset", :geocode => "13046"},
      'Lovell' => {:county => "Oxford", :geocode => "09023"},
      'Lowell' => {:county => "Penobscot", :geocode => "10042"},
      'Lowelltown Twp' => {:county => "Franklin", :geocode => "04037"},
      'Lower Cupsuptic Twp' => {:county => "Oxford", :geocode => "09046"},
      'Lubec' => {:county => "Washington", :geocode => "15031"},
      'Ludlow' => {:county => "Aroostook", :geocode => "02038"},
      'Lyman' => {:county => "York", :geocode => "16016"},
      'Machias' => {:county => "Washington", :geocode => "15032"},
      'Machiasport' => {:county => "Washington", :geocode => "15033"},
      'Macwahoc Plt' => {:county => "Aroostook", :geocode => "02039"},
      'Madawaska' => {:county => "Aroostook", :geocode => "02040"},
      'Madison' => {:county => "Somerset", :geocode => "13025"},
      'Madrid Twp' => {:county => "Franklin", :geocode => "04016"},
      'Magalloway Plt' => {:county => "Oxford", :geocode => "09024"},
      'Manchester' => {:county => "Kennebec", :geocode => "06013"},
      'Mapleton' => {:county => "Aroostook", :geocode => "02041"},
      'Mariaville' => {:county => "Hancock", :geocode => "05019"},
      'Marion Twp' => {:county => "Washington", :geocode => "15034"},
      'Mars Hill' => {:county => "Aroostook", :geocode => "02042"},
      'Marshfield' => {:county => "Washington", :geocode => "15035"},
      'Masardis' => {:county => "Aroostook", :geocode => "02043"},
      'Mason Twp' => {:county => "Oxford", :geocode => "09025"},
      'Matinicus Isle Plt' => {:county => "Knox", :geocode => "07007"},
      'Mattamiscontis Twp' => {:county => "Penobscot", :geocode => "10043"},
      'Mattawamkeag' => {:county => "Penobscot", :geocode => "10044"},
      'Maxfield' => {:county => "Penobscot", :geocode => "10045"},
      'Mayfield Twp' => {:county => "Somerset", :geocode => "13026"},
      'Mechanic Falls' => {:county => "Androscoggin", :geocode => "01009"},
      'Meddybemps' => {:county => "Washington", :geocode => "15036"},
      'Medford' => {:county => "Piscataquis", :geocode => "11015"},
      'Medway' => {:county => "Penobscot", :geocode => "10046"},
      'Mercer' => {:county => "Somerset", :geocode => "13027"},
      'Merrill' => {:county => "Aroostook", :geocode => "02044"},
      'Mexico' => {:county => "Oxford", :geocode => "09026"},
      'Milbridge' => {:county => "Washington", :geocode => "15037"},
      'Milford' => {:county => "Penobscot", :geocode => "10047"},
      'Millinocket' => {:county => "Penobscot", :geocode => "10048"},
      'Milo' => {:county => "Piscataquis", :geocode => "11016"},
      'Milton Twp' => {:county => "Oxford", :geocode => "09027"},
      'Minot' => {:county => "Androscoggin", :geocode => "01010"},
      'Misery Gore Twp' => {:county => "Somerset", :geocode => "13048"},
      'Misery Twp' => {:county => "Somerset", :geocode => "13047"},
      'Molunkus Twp' => {:county => "Aroostook", :geocode => "02045"},
      'Monhegan Island Plt' => {:county => "Lincoln", :geocode => "08010"},
      'Monmouth' => {:county => "Kennebec", :geocode => "06014"},
      'Monroe' => {:county => "Waldo", :geocode => "14012"},
      'Monson' => {:county => "Piscataquis", :geocode => "11017"},
      'Monticello' => {:county => "Aroostook", :geocode => "02046"},
      'Montville' => {:county => "Waldo", :geocode => "14013"},
      'Moose River' => {:county => "Somerset", :geocode => "13028"},
      'Moro Plt' => {:county => "Aroostook", :geocode => "02047"},
      'Morrill' => {:county => "Waldo", :geocode => "14014"},
      'Moscow' => {:county => "Somerset", :geocode => "13029"},
      'Mount Chase' => {:county => "Penobscot", :geocode => "10049"},
      'Mount Desert' => {:county => "Hancock", :geocode => "05020"},
      'Mount Vernon' => {:county => "Kennebec", :geocode => "06015"},
      'Moxie Gore' => {:county => "Somerset", :geocode => "13030"},
      'Naples' => {:county => "Cumberland", :geocode => "03013"},
      'Nashville Plt' => {:county => "Aroostook", :geocode => "02048"},
      'New Canada' => {:county => "Aroostook", :geocode => "02049"},
      'New Gloucester' => {:county => "Cumberland", :geocode => "03014"},
      'New Limerick' => {:county => "Aroostook", :geocode => "02050"},
      'New Portland' => {:county => "Somerset", :geocode => "13031"},
      'New Sharon' => {:county => "Franklin", :geocode => "04017"},
      'New Sweden' => {:county => "Aroostook", :geocode => "02051"},
      'New Vineyard' => {:county => "Franklin", :geocode => "04018"},
      'Newburgh' => {:county => "Penobscot", :geocode => "10050"},
      'Newcastle' => {:county => "Lincoln", :geocode => "08011"},
      'Newfield' => {:county => "York", :geocode => "16017"},
      'Newport' => {:county => "Penobscot", :geocode => "10051"},
      'Newry' => {:county => "Oxford", :geocode => "09028"},
      'No 1 R 7' => {:county => "Penobscot", :geocode => "10053"},
      'No 1 R 9' => {:county => "Piscataquis", :geocode => "11033"},
      'No 10 R 3' => {:county => "Washington", :geocode => "15050"},
      'No 10 So Div' => {:county => "Hancock", :geocode => "05024"},
      'No 14 Twp' => {:county => "Washington", :geocode => "15039"},
      'No 18 Ea Div' => {:county => "Washington", :geocode => "15041"},
      'No 19 Ea Div' => {:county => "Washington", :geocode => "15042"},
      'No 2 A Gore' => {:county => "Piscataquis", :geocode => "11028"},
      'No 2 R 10' => {:county => "Piscataquis", :geocode => "11048"},
      'No 2 R 6' => {:county => "Penobscot", :geocode => "10052"},
      'No 2 R 7' => {:county => "Penobscot", :geocode => "10054"},
      'No 2 R 8' => {:county => "Penobscot", :geocode => "10055"},
      'No 2 R 9' => {:county => "Piscataquis", :geocode => "11042"},
      'No 21 Twp' => {:county => "Washington", :geocode => "15040"},
      'No 22 M Div' => {:county => "Hancock", :geocode => "05025"},
      'No 24 Mid Div' => {:county => "Washington", :geocode => "15045"},
      'No 26 Ea Div' => {:county => "Washington", :geocode => "15043"},
      'No 27 Ea Div' => {:county => "Washington", :geocode => "15044"},
      'No 28 M Div' => {:county => "Hancock", :geocode => "05026"},
      'No 29 Mid Div' => {:county => "Washington", :geocode => "15046"},
      'No 3 R 10' => {:county => "Piscataquis", :geocode => "11043"},
      'No 3 R 9' => {:county => "Piscataquis", :geocode => "11047"},
      'No 33 Plt' => {:county => "Hancock", :geocode => "05027"},
      'No 4 R 10' => {:county => "Piscataquis", :geocode => "11044"},
      'No 4 R 9' => {:county => "Piscataquis", :geocode => "11032"},
      'No 5 R 9' => {:county => "Piscataquis", :geocode => "11035"},
      'No 6 N Of Weld' => {:county => "Franklin", :geocode => "04019"},
      'No 7 So Div' => {:county => "Hancock", :geocode => "05021"},
      'No 8 Plt' => {:county => "Hancock", :geocode => "05022"},
      'No 8 R 3' => {:county => "Washington", :geocode => "15049"},
      'No 8 R 4' => {:county => "Washington", :geocode => "15051"},
      'No 9 So Div' => {:county => "Hancock", :geocode => "05023"},
      'Nobleboro' => {:county => "Lincoln", :geocode => "08012"},
      'Norridgewock' => {:county => "Somerset", :geocode => "13032"},
      'North Berwick' => {:county => "York", :geocode => "16018"},
      'North Haven' => {:county => "Knox", :geocode => "07008"},
      'North Penobscot' => {:county => "Penobscot", :geocode => "10078"},
      'North Yarmouth' => {:county => "Cumberland", :geocode => "03015"},
      'Northfield' => {:county => "Washington", :geocode => "15038"},
      'Northport' => {:county => "Waldo", :geocode => "14015"},
      'Norway' => {:county => "Oxford", :geocode => "09029"},
      'Not A Maine Resident' => {:county => "Non Maine Resident", :geocode => "RESID"},
      'Oakfield' => {:county => "Aroostook", :geocode => "02063"},
      'Oakland' => {:county => "Kennebec", :geocode => "06016"},
      'Ogunquit' => {:county => "York", :geocode => "16029"},
      'Old Orchard Beach' => {:county => "York", :geocode => "16020"},
      'Old Town' => {:county => "Penobscot", :geocode => "10056"},
      'Orient' => {:county => "Aroostook", :geocode => "02064"},
      'Orland' => {:county => "Hancock", :geocode => "05028"},
      'Orneville Twp' => {:county => "Piscataquis", :geocode => "11018"},
      'Orono' => {:county => "Penobscot", :geocode => "10057"},
      'Orrington' => {:county => "Penobscot", :geocode => "10058"},
      'Osborn' => {:county => "Hancock", :geocode => "05029"},
      'Otis' => {:county => "Hancock", :geocode => "05030"},
      'Otisfield' => {:county => "Oxford", :geocode => "09047"},
      'Out Of State' => {:county => "Not In State", :geocode => "00000"},
      'Owls Head' => {:county => "Knox", :geocode => "07009"},
      'Oxbow Plt' => {:county => "Aroostook", :geocode => "02065"},
      'Oxford' => {:county => "Oxford", :geocode => "09030"},
      'Palermo' => {:county => "Waldo", :geocode => "14016"},
      'Palmyra' => {:county => "Somerset", :geocode => "13033"},
      'Paris' => {:county => "Oxford", :geocode => "09031"},
      'Parkman' => {:county => "Piscataquis", :geocode => "11019"},
      'Parlin Pond Twp' => {:county => "Somerset", :geocode => "13034"},
      'Parsonsfield' => {:county => "York", :geocode => "16021"},
      'Passadumkeag' => {:county => "Penobscot", :geocode => "10059"},
      'Patten' => {:county => "Penobscot", :geocode => "10060"},
      'Peaks Island' => {:county => "Cumberland", :geocode => "03027"},
      'Pembroke' => {:county => "Washington", :geocode => "15052"},
      'Penobscot' => {:county => "Hancock", :geocode => "05031"},
      'Perham' => {:county => "Aroostook", :geocode => "02066"},
      'Perkins Twp' => {:county => "Franklin", :geocode => "04020"},
      'Perkins Twp Swan Island' => {:county => "Sagadahoc", :geocode => "12006"},
      'Perry' => {:county => "Washington", :geocode => "15053"},
      'Peru' => {:county => "Oxford", :geocode => "09032"},
      'Peter Dana Pt Res' => {:county => "Washington", :geocode => "15066"},
      'Phillips' => {:county => "Franklin", :geocode => "04021"},
      'Phippsburg' => {:county => "Sagadahoc", :geocode => "12007"},
      'Pittsfield' => {:county => "Somerset", :geocode => "13035"},
      'Pittston' => {:county => "Kennebec", :geocode => "06017"},
      'Pleasant Point' => {:county => "Washington", :geocode => "15067"},
      'Pleasant Ridge Plt' => {:county => "Somerset", :geocode => "13036"},
      'Plt 30 Mid Div' => {:county => "Washington", :geocode => "15047"},
      'Plt 31 Mid Div' => {:county => "Washington", :geocode => "15048"},
      'Plymouth' => {:county => "Penobscot", :geocode => "10061"},
      'Poland' => {:county => "Androscoggin", :geocode => "01011"},
      'Portage Lake' => {:county => "Aroostook", :geocode => "02067"},
      'Porter' => {:county => "Oxford", :geocode => "09033"},
      'Portland' => {:county => "Cumberland", :geocode => "03017"},
      'Pownal' => {:county => "Cumberland", :geocode => "03018"},
      'Prentiss Plt' => {:county => "Penobscot", :geocode => "10062"},
      'Presque Isle' => {:county => "Aroostook", :geocode => "02068"},
      'Princeton' => {:county => "Washington", :geocode => "15054"},
      'Prospect' => {:county => "Waldo", :geocode => "14017"},
      'Randolph' => {:county => "Kennebec", :geocode => "06018"},
      'Rangeley' => {:county => "Franklin", :geocode => "04022"},
      'Rangeley Plt' => {:county => "Franklin", :geocode => "04023"},
      'Raymond' => {:county => "Cumberland", :geocode => "03019"},
      'Readfield' => {:county => "Kennebec", :geocode => "06019"},
      'Reed Plt' => {:county => "Aroostook", :geocode => "02069"},
      'Richmond' => {:county => "Sagadahoc", :geocode => "12008"},
      'Riley Twp' => {:county => "Oxford", :geocode => "09034"},
      'Ripley' => {:county => "Somerset", :geocode => "13037"},
      'Robbinston' => {:county => "Washington", :geocode => "15055"},
      'Rockland' => {:county => "Knox", :geocode => "07010"},
      'Rockport' => {:county => "Knox", :geocode => "07011"},
      'Rockwood Twp' => {:county => "Somerset", :geocode => "13049"},
      'Rome' => {:county => "Kennebec", :geocode => "06020"},
      'Roque Bluffs' => {:county => "Washington", :geocode => "15056"},
      'Roxbury' => {:county => "Oxford", :geocode => "09035"},
      'Rumford' => {:county => "Oxford", :geocode => "09036"},
      'Sabattus' => {:county => "Androscoggin", :geocode => "01014"},
      'Saco' => {:county => "York", :geocode => "16022"},
      'Saint Agatha' => {:county => "Aroostook", :geocode => "02070"},
      'Saint Albans' => {:county => "Somerset", :geocode => "13038"},
      'Saint Francis' => {:county => "Aroostook", :geocode => "02071"},
      'Saint George' => {:county => "Knox", :geocode => "07012"},
      'Saint John Plt' => {:county => "Aroostook", :geocode => "02072"},
      'Salem Twp' => {:county => "Franklin", :geocode => "04024"},
      'Sandwich Academy Grant Twp' => {:county => "Somerset", :geocode => "13050"},
      'Sandy Bay Twp' => {:county => "Somerset", :geocode => "13039"},
      'Sandy River Plt' => {:county => "Franklin", :geocode => "04025"},
      'Sanford' => {:county => "York", :geocode => "16023"},
      'Sangerville' => {:county => "Piscataquis", :geocode => "11020"},
      'Sapling Twp' => {:county => "Somerset", :geocode => "13051"},
      'Scarborough' => {:county => "Cumberland", :geocode => "03020"},
      'Searsmont' => {:county => "Waldo", :geocode => "14018"},
      'Searsport' => {:county => "Waldo", :geocode => "14019"},
      'Sebago' => {:county => "Cumberland", :geocode => "03021"},
      'Sebec' => {:county => "Piscataquis", :geocode => "11021"},
      'Seboeis Plt' => {:county => "Penobscot", :geocode => "10063"},
      'Sedgwick' => {:county => "Hancock", :geocode => "05032"},
      'Shapleigh' => {:county => "York", :geocode => "16024"},
      'Shawmut' => {:county => "Somerset", :geocode => "13018"},
      'Sherman' => {:county => "Aroostook", :geocode => "02073"},
      'Shirley' => {:county => "Piscataquis", :geocode => "11022"},
      'Sidney' => {:county => "Kennebec", :geocode => "06021"},
      'Silver Ridge Twp' => {:county => "Aroostook", :geocode => "02074"},
      'Skowhegan' => {:county => "Somerset", :geocode => "13040"},
      'Smithfield' => {:county => "Somerset", :geocode => "13041"},
      'Smyrna' => {:county => "Aroostook", :geocode => "02075"},
      'Solon' => {:county => "Somerset", :geocode => "13042"},
      'Somerville' => {:county => "Lincoln", :geocode => "08013"},
      'Sorrento' => {:county => "Hancock", :geocode => "05033"},
      'South Berwick' => {:county => "York", :geocode => "16025"},
      'South Bristol' => {:county => "Lincoln", :geocode => "08014"},
      'South Portland' => {:county => "Cumberland", :geocode => "03022"},
      'South Thomaston' => {:county => "Knox", :geocode => "07013"},
      'Southport' => {:county => "Lincoln", :geocode => "08015"},
      'Southwest Harbor' => {:county => "Hancock", :geocode => "05034"},
      'Springfield' => {:county => "Penobscot", :geocode => "10064"},
      'Springvale' => {:county => "York", :geocode => "16030"},
      'Staceyville' => {:county => "Penobscot", :geocode => "10065"},
      'Standish' => {:county => "Cumberland", :geocode => "03023"},
      'Starks' => {:county => "Somerset", :geocode => "13043"},
      'Stetson' => {:county => "Penobscot", :geocode => "10066"},
      'Steuben' => {:county => "Washington", :geocode => "15057"},
      'Stockholm' => {:county => "Aroostook", :geocode => "02076"},
      'Stockton Springs' => {:county => "Waldo", :geocode => "14020"},
      'Stoneham' => {:county => "Oxford", :geocode => "09037"},
      'Stonington' => {:county => "Hancock", :geocode => "05035"},
      'Stow' => {:county => "Oxford", :geocode => "09038"},
      'Strong' => {:county => "Franklin", :geocode => "04026"},
      'Sullivan' => {:county => "Hancock", :geocode => "05036"},
      'Summit Twp' => {:county => "Penobscot", :geocode => "10067"},
      'Sumner' => {:county => "Oxford", :geocode => "09039"},
      'Surry' => {:county => "Hancock", :geocode => "05037"},
      'Swans Island' => {:county => "Hancock", :geocode => "05038"},
      'Swanville' => {:county => "Waldo", :geocode => "14021"},
      'Sweden' => {:county => "Oxford", :geocode => "09040"},
      'T1 R4 WELS' => {:county => "Aroostook", :geocode => "02052"},
      'T1 R5 WELS' => {:county => "Aroostook", :geocode => "02056"},
      'T1 R8 WELS' => {:county => "Penobscot", :geocode => "10072"},
      'T11 R14 WELS' => {:county => "Aroostook", :geocode => "02086"},
      'T11 R4 WELS' => {:county => "Aroostook", :geocode => "02053"},
      'T15 R6 WELS' => {:county => "Aroostook", :geocode => "02062"},
      'T16 R4 WELS' => {:county => "Aroostook", :geocode => "02054"},
      'T17 R4 WELS' => {:county => "Aroostook", :geocode => "02055"},
      'T17 R5 WELS' => {:county => "Aroostook", :geocode => "02060"},
      'T17 R6 WELS' => {:county => "Aroostook", :geocode => "02061"},
      'T5 R7 WELS' => {:county => "Penobscot", :geocode => "10074"},
      'T7 R5 WELS' => {:county => "Aroostook", :geocode => "02057"},
      'T8 R5 WELS' => {:county => "Aroostook", :geocode => "02058"},
      'T9 R5 WELS' => {:county => "Aroostook", :geocode => "02059"},
      'Talmadge' => {:county => "Washington", :geocode => "15058"},
      'Taunton Raynham Twp' => {:county => "Somerset", :geocode => "13052"},
      'Temple' => {:county => "Franklin", :geocode => "04027"},
      'The Forks Plt' => {:county => "Somerset", :geocode => "13044"},
      'Thomaston' => {:county => "Knox", :geocode => "07014"},
      'Thorndike' => {:county => "Waldo", :geocode => "14022"},
      'Topsfield' => {:county => "Washington", :geocode => "15059"},
      'Topsham' => {:county => "Sagadahoc", :geocode => "12009"},
      'Township E' => {:county => "Franklin", :geocode => "04015"},
      'Tremont' => {:county => "Hancock", :geocode => "05039"},
      'Trenton' => {:county => "Hancock", :geocode => "05040"},
      'Trescott Twp' => {:county => "Washington", :geocode => "15060"},
      'Troy' => {:county => "Waldo", :geocode => "14023"},
      'Turner' => {:county => "Androscoggin", :geocode => "01012"},
      'Twombly' => {:county => "Penobscot", :geocode => "10076"},
      'Union' => {:county => "Knox", :geocode => "07015"},
      'Unity' => {:county => "Waldo", :geocode => "14024"},
      'Unity Twp' => {:county => "Kennebec", :geocode => "06022"},
      'Upton' => {:county => "Oxford", :geocode => "09041"},
      'Van Buren' => {:county => "Aroostook", :geocode => "02077"},
      'Vanceboro' => {:county => "Washington", :geocode => "15061"},
      'Vassalboro' => {:county => "Kennebec", :geocode => "06023"},
      'Veazie' => {:county => "Penobscot", :geocode => "10068"},
      'Verona Island' => {:county => "Hancock", :geocode => "05041"},
      'Vienna' => {:county => "Kennebec", :geocode => "06024"},
      'Vinalhaven' => {:county => "Knox", :geocode => "07016"},
      'Wade' => {:county => "Aroostook", :geocode => "02078"},
      'Waite' => {:county => "Washington", :geocode => "15062"},
      'Waldo' => {:county => "Waldo", :geocode => "14025"},
      'Waldoboro' => {:county => "Lincoln", :geocode => "08016"},
      'Wales' => {:county => "Androscoggin", :geocode => "01013"},
      'Wallagrass' => {:county => "Aroostook", :geocode => "02079"},
      'Waltham' => {:county => "Hancock", :geocode => "05042"},
      'Warren' => {:county => "Knox", :geocode => "07017"},
      'Washburn' => {:county => "Aroostook", :geocode => "02080"},
      'Washington' => {:county => "Knox", :geocode => "07018"},
      'Washington Twp' => {:county => "Franklin", :geocode => "04028"},
      'Waterboro' => {:county => "York", :geocode => "16026"},
      'Waterford' => {:county => "Oxford", :geocode => "09042"},
      'Waterville' => {:county => "Kennebec", :geocode => "06025"},
      'Wayne' => {:county => "Kennebec", :geocode => "06026"},
      'Webster Plt' => {:county => "Penobscot", :geocode => "10069"},
      'Weld' => {:county => "Franklin", :geocode => "04029"},
      'Wellington' => {:county => "Piscataquis", :geocode => "11023"},
      'Wells' => {:county => "York", :geocode => "16027"},
      'Wesley' => {:county => "Washington", :geocode => "15063"},
      'West Bath' => {:county => "Sagadahoc", :geocode => "12010"},
      'West Forks Plt' => {:county => "Somerset", :geocode => "13045"},
      'West Gardiner' => {:county => "Kennebec", :geocode => "06027"},
      'West Paris' => {:county => "Oxford", :geocode => "09045"},
      'Westbrook' => {:county => "Cumberland", :geocode => "03024"},
      'Westfield' => {:county => "Aroostook", :geocode => "02081"},
      'Westmanland' => {:county => "Aroostook", :geocode => "02082"},
      'Weston' => {:county => "Aroostook", :geocode => "02083"},
      'Westport' => {:county => "Lincoln", :geocode => "08017"},
      'Whitefield' => {:county => "Lincoln", :geocode => "08018"},
      'Whiting' => {:county => "Washington", :geocode => "15064"},
      'Whitney' => {:county => "Penobscot", :geocode => "10077"},
      'Whitneyville' => {:county => "Washington", :geocode => "15065"},
      'Williamsburg Twp' => {:county => "Piscataquis", :geocode => "11024"},
      'Willimantic' => {:county => "Piscataquis", :geocode => "11025"},
      'Wilton' => {:county => "Franklin", :geocode => "04030"},
      'Windham' => {:county => "Cumberland", :geocode => "03025"},
      'Windsor' => {:county => "Kennebec", :geocode => "06028"},
      'Winn' => {:county => "Penobscot", :geocode => "10070"},
      'Winslow' => {:county => "Kennebec", :geocode => "06029"},
      'Winter Harbor' => {:county => "Hancock", :geocode => "05043"},
      'Winterport' => {:county => "Waldo", :geocode => "14026"},
      'Winterville Plt' => {:county => "Aroostook", :geocode => "02084"},
      'Winthrop' => {:county => "Kennebec", :geocode => "06030"},
      'Wiscasset' => {:county => "Lincoln", :geocode => "08019"},
      'Woodland' => {:county => "Aroostook", :geocode => "02085"},
      'Woodstock' => {:county => "Oxford", :geocode => "09043"},
      'Woodville' => {:county => "Penobscot", :geocode => "10071"},
      'Woolwich' => {:county => "Sagadahoc", :geocode => "12011"},
      'Wyman Twp' => {:county => "Franklin", :geocode => "04031"},
      'Yarmouth' => {:county => "Cumberland", :geocode => "03026"},
      'York' => {:county => "York", :geocode => "16028"}
    }
  end
  # rubocop:enable Metrics/MethodLength
end
# rubocop:enable Metrics/ModuleLength
