####################
# Rails prod image #
####################

ARG COMMIT_SHA
ARG CLIENT
ARG BRANCH=trunk

FROM public.ecr.aws/ideacrew/enroll:${BRANCH}-${COMMIT_SHA}-${CLIENT}

# Switch back to root to install system libraries
USER root

RUN apt-get update \
    && apt-get -yq dist-upgrade \
    && apt-get install -y \
      libssh2-1

RUN curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o "awscliv2.zip" && unzip awscliv2.zip && ./aws/install && rm awscliv2.zip
