---
registry:
  - namespace:
    - :enroll_app
    - :aca_individual_market
    - :catalog_2021
    - :osse_eligibility_criteria
    features:
        - key: :aca_ivl_osse_subsidy_2021
          item: :aca_ivl_osse_subsidy_2021
          is_enabled: <%= ENV['IVL_OSSE_ELIGIBILITY_2021_IS_ENABLED'] || false %>
  - namespace:
    - :enroll_app
    - :aca_individual_market
    - :catalog_2022
    - :osse_eligibility_criteria
    features:
        - key: :aca_ivl_osse_subsidy_2022
          item: :aca_ivl_osse_subsidy_2022
          is_enabled: <%= ENV['IVL_OSSE_ELIGIBILITY_2022_IS_ENABLED'] || false %>
  - namespace:
    - :enroll_app
    - :aca_individual_market
    - :catalog_2023
    - :osse_eligibility_criteria
    features:
        - key: :aca_ivl_osse_subsidy_2023
          item: :aca_ivl_osse_subsidy_2023
          is_enabled: <%= ENV['IVL_OSSE_ELIGIBILITY_2023_IS_ENABLED'] || false %>
