---
registry:
  - namespace:
      - :enroll_app
      - :aca_individual_market
      - :eligibilities
    features:
      - key: :'gid://enroll_app/Family'
        is_enabled: true
        settings:
          - key: :eligibility_items
            item:
              - :aptc_csr_credit
              - :aca_individual_market_eligibility
              - :health_product_enrollment_status
              - :dental_product_enrollment_status
      - key: :verification_document_due_in_days
        item: 95
        is_enabled: true
  - namespace:
      - :enroll_app
      - :aca_individual_market
      - :eligibilities
      - :eligibility_items
    features:
      - key: :aptc_csr_credit
        is_enabled: true
        settings:
          - key: :evidence_items
            item:
              - :income_evidence
              - :esi_evidence
              - :non_esi_evidence
              - :local_mec_evidence
      - key: :aca_individual_market_eligibility
        is_enabled: true
        settings:
          - key: :evidence_items
            item:
              - :immigration_status
              - :citizenship
              - :american_indian_status
              - :social_security_number
      - key: :health_product_enrollment_status
        is_enabled: false
        settings:
          - key: :evidence_items
            item:
              - :health_product_enrollment_evidence
      - key: :dental_product_enrollment_status
        is_enabled: false
        settings:
          - key: :evidence_items
            item:
              - :dental_product_enrollment_evidence
  - namespace:
      - :enroll_app
      - :aca_individual_market
      - :eligibilities
      - :eligibility_items
      - :evidence_items
    features:
      - key: :income_evidence
        is_enabled: true
        settings:
          - key: :subject_ref
            item: 'gid://enroll_app/Family::FamilyMember'
          - key: :evidence_ref
            item: 'gid://enroll_app/FinancialAssitance::Application'
      - key: :esi_evidence
        is_enabled: true
        settings:
          - key: :subject_ref
            item: 'gid://enroll_app/Family::FamilyMember'
          - key: :evidence_ref
            item: 'gid://enroll_app/FinancialAssitance::Application'
      - key: :non_esi_evidence
        is_enabled: true
        settings:
          - key: :subject_ref
            item: 'gid://enroll_app/Family::FamilyMember'
          - key: :evidence_ref
            item: 'gid://enroll_app/FinancialAssitance::Application'
      - key: :local_mec_evidence
        is_enabled: true
        settings:
          - key: :subject_ref
            item: 'gid://enroll_app/Family::FamilyMember'
          - key: :evidence_ref
            item: 'gid://enroll_app/FinancialAssitance::Application'
      - key: :immigration_status
        is_enabled: true
        settings:
          - key: :subject_ref
            item: 'gid://enroll_app/Family::FamilyMember'
          - key: :evidence_ref
            item: 'gid://enroll_app/Person'
      - key: :citizenship
        is_enabled: true
        settings:
          - key: :subject_ref
            item: 'gid://enroll_app/Family::FamilyMember'
          - key: :evidence_ref
            item: 'gid://enroll_app/Person'
      - key: :american_indian_status
        is_enabled: true
        settings:
          - key: :subject_ref
            item: 'gid://enroll_app/Family::FamilyMember'
          - key: :evidence_ref
            item: 'gid://enroll_app/Person'
      - key: :social_security_number
        is_enabled: true
        settings:
          - key: :subject_ref
            item: 'gid://enroll_app/Family::FamilyMember'
          - key: :evidence_ref
            item: 'gid://enroll_app/Person'
      - key: :health_product_enrollment_evidence
        is_enabled: true
        settings:
          - key: :subject_ref
            item: 'gid://enroll_app/Family::FamilyMember'
          - key: :evidence_ref
            item: 'gid://enroll_app/HbxEnrollment'
      - key: :dental_product_enrollment_evidence
        is_enabled: true
        settings:
          - key: :subject_ref
            item: 'gid://enroll_app/Family::FamilyMember'
          - key: :evidence_ref
            item: 'gid://enroll_app/HbxEnrollment'
