---
asyncapi: 2.0.0
info:
  title: Enroll App
  version: 0.1.0
  description: AMQP Publishconfiguration for the Enroll App services
  contact:
    name: IdeaCrew
    url: https://ideacrew.com
    email: info@ideacrew.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  production:
    url: "amqp://localhost:5672/"
    protocol: :amqp
    protocolVersion: "0.9.2"
    description: RabbitMQ Production Server
  test:
    url: "amqp://localhost:5672/"
    protocol: :amqp
    protocolVersion: "0.9.2"
    description: RabbitMQ Test Server
  development:
    url: amqp://localhost:5672/
    protocol: amqp
    protocolVersion: 0.9.2
    description: RabbitMQ Development Server
channels:
  enroll.iap.applications.determine_eligibility:
    bindings:
      amqp:
        is: :routing_key
        exchange:
          name: enroll.iap.applications
          type: topic
          content_type: application/json
          durable: true
          auto_delete: false
          vhost: /
        binding_version: "0.2.0"
    publish:
      operationId: enroll.iap.applications.determine_eligibility
      summary: Events - eligibility determination Request
      bindings:
        amqp:
          app_id: enroll
          type: enroll.iap.applications
          routing_key: enroll.iap.applications.determine_eligibility
          expiration: 100_000
          deliveryMode: 2
          mandatory: true
          timestamp: true
          content_type: application/json
          bindingVersion: 0.2.0
   