USER_MAILER_TRANSLATIONS = {
  "en.user_mailer.generic_consumer.bottom_text" => "<p class='heading'>Questions or need help?</p><p>Call the %{contact_center_name} at %{marketplace_phone} or go online to <a href='%{site_home_business_url}'>CoverME website</a>.</p>",
  "en.user_mailer.generic_notice_alert.full_text" => "<p>Hi %{first_name},</p><p>You have a new message from %{site_short_name} about your health coverage that may require action. Login to your account to read this message.<br><a href=%{site_home_business_url} class='button-link'>Log In To %{site_short_name}</a><br><p>Questions? Call us at %{contact_center_phone_number}.</p><p>The %{site_short_name} Team</p>",
  "en.user_mailer.broker_application_confirmation.full_text" => "<p>Hi %{first_name},</p><p>Now that you’ve registered, we will review your application and confirm that you have:</p<br><ul><li><p>Completed the <a href=%{training_link}> %{site_short_name} training</a> provided by the %{site_short_name} Consumer Assistance Center</p></li><li><p>Have an active producer license with health authority with the %{state_name} Bureau of Insurance</p></li></ul><p>If you have met all of the requirements, you’ll get an email from %{site_short_name} in the next 7-10 business days with a link to set up your %{site_short_name} password. Registration and certification with %{site_short_name} does not guarantee appointments with carriers. You still need to work with carriers to secure appointments.</p><p> Questions? Call us at %{contact_center_phone_number}</p><p>The %{site_short_name} Team</p>",
  "en.user_mailer.broker_invitation_email.full_text" => "<p>Hi %{first_name},</p><p>Your application to assist consumers on %{site_short_name} has been approved. Set up your account to get started. By setting up your account, you affirm that you have read and agreed to the <a href='https://www.coverme.gov/brokeragreement' target='_blank'>CoverME.gov broker agreement</a>.</p><br><a href=%{invitation_url} class='button-link'>Set Up Account</a><br><p>Questions? Call us at %{contact_center_phone_number}.</p><p>The %{site_short_name} Team</p>",
  "en.user_mailer.broker_staff_invitation_email.full_text"=> "<p>Hi %{person_name},</p><p> Your application to assist consumers on %{site_short_name} has been approved. Set up your account to get started.</p><a href=%{invitation_url} class='button-link'>Set Up Account</a> <br> <p>Questions? Call us at %{contact_center_phone_number}.</p><p>The %{site_short_name} Team</p>",
  "en.user_mailer.broker_pending_missing_training_completed_carrier.full_text" => "<p>Hi %{applicant_name},</p><p>We’ve reviewed your application to assist consumers on %{site_short_name}. You have not completed the required trainings. Once you have met all of the requirements, you’ll get an email from %{site_short_name} in 7-10 business days with a link to set up your %{site_short_name} password.</p><br><a href=%{training_link} class='button-link'>Go To Training</a><br><br><p>Questions? Call us at %{contact_center_phone_number}.</p><p>The %{site_short_name} Team</p>",
  "en.user_mailer.broker_denied.full_text" => "<p>Hi %{applicant_name},</p><p>We’ve denied your application to assist consumers on %{site_short_name} because you did not meet the requirements, or because we already had an application for you.</p><p>Questions? Call us at %{contact_center_phone_number}.</p><p>The %{site_short_name} Team</p>",
  "en.user_mailer.broker_invitation.message_to_broker" => "<html><body>Hello %{broker_name},<br/>You received message from %{person_name} with help regarding plan shopping page.<br/>Here is the information requested:><br/>%{message_body}</body></html>",
  "en.user_mailer.new_client_notification.full_text" => "<p>Hi %{person_name},</p><p>A new client has chosen you on %{site_short_name}.</p><p>Login to your account to assist this client.</p><br><a href=%{site_home_business_url} class='button-link'>Log In To %{site_short_name}</a><br><p>Questions? Call us at %{contact_center_phone_number}.</p><p>The %{site_short_name} Team</p>",
  "en.user_mailer.broker_pending_completed_training_missing_carrier.full_text" => "<p>Hi %{applicant_name},</p> <p>We’ve reviewed your application to assist consumers on {site_short_name}. You have not completed the required trainings. Once you have met all of the requirements, you’ll get an email from %{site_short_name} in 7-10 business days with a link to set up your %{site_short_name} password.</p><a href=%{training_link} class='button-link'>Go To Training</a><br><p>Questions? Call us at %{contact_center_phone_number}.</p><p>The %{site_short_name} Team</p>",
  "en.user_mailer.reset_password_instructions.full_text" => "<p>Hi,</p><p>We’re responding to your password reset request. If it was you, please change your password below.</p><br><a href=%{edit_password_url}>Change My Password</a><br><p>If you didn't request this, please ignore this email. Your password won't change until you access the link above and create a new one.</p><p>Questions? Call us at %{contact_center_phone_number}.</p><p>The %{site_short_name} Team</p>",
  "en.user_mailer.account_transfer_success_notification.full_text" => "<p>Hi %{person_name},</p><p>It’s time to take action to get covered on %{site_short_name}. %{site_short_name} is %{state_name}’s health insurance marketplace where you can find health insurancethat meets your needs and budget. You may be eligible for financial help with premiums and other costs.</p><p><strong>Here’s what you need to do to get covered:</strong></p><ol><li> Go to ${site_home_business_url} and login to your account, or create an account if you don’t have one already. If you are creating an account, be sure to list your own information first, before telling us about anyone in your family. This will help us find your application and save you time. </li><li> Review your application. Review all the information on your application and update it if it’s wrong. There may be missing information that you need to add, including information on the letter the %{medicaid_or_chip_agency_long_name} sent you. </li><li>Choose a health insurance plan. Remember, there is limited time to sign up.</li></ol><br><a href=%{site_home_business_url} class='button-link'>Go To %{site_short_name}</a><br><p>Why you’re getting this email </p><p>You recently applied for health coverage. %{medicaid_or_chip_agency_long_name} made a decision about your eligibility for %{medicaid_or_chip_program_short_name} and sent you a letter. Based on that decision, they also sent your application to %{site_short_name}.</p><p>Questions? We’re here to help.</p><p>The %{site_short_name} Team</p>"
}
