# frozen_string_literal: true

RSpec.shared_context 'cms ME simple_scenarios test_case_d', :shared_context => :metadata do
  let(:current_date) { Date.today }
  let(:member_dob) { Date.new(current_date.year - 22, current_date.month, current_date.beginning_of_month.day) }
  let(:aptc_effective_date) { Date.today.next_month.beginning_of_month }
  let(:notice_options) { { send_eligibility_notices: true, send_open_enrollment_notices: false, :paper_notification => true} }
  let(:response_payload) do
    { :family_reference => {:hbx_id => "10011"},
      :assistance_year => current_date.year,
      :aptc_effective_date => aptc_effective_date,
      :applicants => [{ :name => { :first_name => "Gerald", :last_name => "Rivers" },
                        :identifying_information => { :has_ssn => false },
                        :demographic => { :gender => "Male",
                                          :dob => member_dob,
                                          :is_veteran_or_active_military => false },
                        :attestation => { :is_incarcerated => false,
                                          :is_self_attested_disabled => true,
                                          :is_self_attested_blind => false },
                        :is_primary_applicant => true,
                        :native_american_information => { :indian_tribe_member => false },
                        :citizenship_immigration_status_information => { :citizen_status => "us_citizen",
                                                                         :is_lawful_presence_self_attested => false },
                        :is_applying_coverage => true,
                        :family_member_reference => { :family_member_hbx_id => "1000",
                                                      :first_name => "Gerald",
                                                      :last_name => "Rivers",
                                                      :person_hbx_id => "95",
                                                      :is_primary_family_member => true },
                        :person_hbx_id => "95",
                        :is_required_to_file_taxes => true,
                        :tax_filer_kind => "tax_filer",
                        :is_joint_tax_filing => true,
                        :is_claimed_as_tax_dependent => false,
                        :claimed_as_tax_dependent_by => nil,
                        :student => { :is_student => false },
                        :is_refugee => false,
                        :is_trafficking_victim => false,
                        :foster_care => { :is_former_foster_care => false },
                        :pregnancy_information => { :is_pregnant => false,
                                                    :is_post_partum_period => false,
                                                    :expected_children_count => nil },
                        :is_subject_to_five_year_bar => false,
                        :is_five_year_bar_met => false,
                        :has_job_income => true,
                        :has_self_employment_income => false,
                        :has_unemployment_income => false,
                        :has_other_income => false,
                        :has_deductions => false,
                        :has_enrolled_health_coverage => false,
                        :has_eligible_health_coverage => false,
                        :medicaid_and_chip => { :not_eligible_in_last_90_days => true,
                                                :denied_on => Date.today },
                        :addresses => [{ :has_fixed_address => true,
                                         :kind => "home",
                                         :address_1 => "1234",
                                         :address_3 => "person",
                                         :city => "test",
                                         :county => nil,
                                         :state => "DC",
                                         :zip => "12345",
                                         :country_name => "USA",
                                         :validation_status => "ValidMatch",
                                         :start_on => aptc_effective_date,
                                         :end_on => nil,
                                         :lives_outside_state_temporarily => false }],
                        :incomes => [{ :kind => "wages_and_salaries",
                                       :amount => 16_500.00,
                                       :frequency_kind => "Annually",
                                       :start_on => Date.today.beginning_of_year }],
                        :is_medicare_eligible => false,
                        :has_insurance => false,
                        :has_state_health_benefit => false,
                        :had_prior_insurance => false,
                        :age_of_applicant => 22,
                        :is_self_attested_long_term_care => false,
                        :hours_worked_per_week => 0,
                        :is_temporarily_out_of_state => false,
                        :is_claimed_as_dependent_by_non_applicant => false,
                        :benchmark_premium =>
                          { :health_only_lcsp_premiums => [{ :member_identifier => "95", :monthly_premium => 430.48 }],
                            :health_only_slcsp_premiums => [{ :member_identifier => "95", :monthly_premium => 496.23 }] },
                        :is_homeless => false,
                        :mitc_income =>
                          { :amount => 14_976,
                            :taxable_interest => 0,
                            :tax_exempt_interest => 0,
                            :taxable_refunds => 0,
                            :alimony => 0,
                            :capital_gain_or_loss => 0,
                            :pensions_and_annuities_taxable_amount => 0,
                            :farm_income_or_loss => 0,
                            :unemployment_compensation => 0,
                            :other_income => 0,
                            :magi_deductions => 0,
                            :adjusted_gross_income => 0,
                            :deductible_part_of_self_employment_tax => 0,
                            :ira_deduction => 0,
                            :student_loan_interest_deduction => 0,
                            :tution_and_fees => 0,
                            :other_magi_eligible_income => 0 },
                        :mitc_relationships => [] }],
      :tax_households => [{ :max_aptc => 496.0,
                            effective_on: Date.today.next_month.beginning_of_month,
                            determined_on: Date.today,
                            annual_tax_household_income: 16_000.0,
                            yearly_expected_contribution: 1_672.20,
                            csr_annual_income_limit: 142_912_000.0,
                            :hbx_id => "12345",
                            :is_insurance_assistance_eligible => "Yes",
                            :tax_household_members => [{
                              :product_eligibility_determination => { :is_ia_eligible => true,
                                                                      :is_medicaid_chip_eligible => false,
                                                                      :is_totally_ineligible => nil,
                                                                      :is_magi_medicaid => false,
                                                                      :is_uqhp_eligible => nil,
                                                                      :is_csr_eligible => true,
                                                                      is_eligible_for_non_magi_reasons: true,
                                                                      :is_gap_filling => true,
                                                                      :csr => "limited",
                                                                      :is_non_magi_medicaid_eligible => false,
                                                                      :is_without_assistance => false,
                                                                      :member_determinations => [{
                                                                        :kind => 'Insurance Assistance Determination',
                                                                        :criteria_met => true,
                                                                        :determination_reasons => [],
                                                                        eligibility_overrides: []
                                                                      }]},
                              :applicant_reference => { :first_name => "Gerald",
                                                        :last_name => "Rivers",
                                                        :dob => member_dob,
                                                        :person_hbx_id => "95" }
                            }] }],
      :relationships => [],
      :us_state => "DC",
      :hbx_id => "200000126",
      :oe_start_on => Date.new(current_date.year, 11, 1),
      notice_options: notice_options,
      :mitc_households => [{ :household_id => "1", :people => [{ :person_id => 95 }] }],
      :mitc_tax_returns => [{ :filers => [{ :person_id => 95 }], :dependents => [] }] }
  end
end

RSpec.shared_context 'application with more than 3 children', :shared_context => :metadata do
  let(:current_date) { Date.today }
  let(:member_dob) { Date.new(current_date.year - 22, current_date.month, current_date.day) }
  let(:aptc_effective_date) { Date.today.next_month.beginning_of_month }
  let(:notice_options) { { send_eligibility_notices: true, send_open_enrollment_notices: false, :paper_notification => true} }

  let(:response_payload_1) do
    {:family_reference => {:hbx_id => "200201356"},
     :assistance_year => 2022,
     :aptc_effective_date => "2022-11-01",
     :years_to_renew => 2027,
     :renewal_consent_through_year => 5,
     :is_ridp_verified => true,
     :is_renewal_authorized => true,
     :applicants =>
      [{:name =>
         {:first_name => "adult2.1",
          :middle_name => nil,
          :last_name => "test",
          :name_sfx => nil,
          :name_pfx => nil},
        :identifying_information =>
         {:encrypted_ssn => "qfl5FpLXZtCR5omSMxhi6IMGvP8HLMVJlA==\n",
          :has_ssn => false},
        :demographic =>
         {:gender => "Male",
          :dob => "2000-01-01",
          :ethnicity => ["", "", "", "", "", "", ""],
          :race => nil,
          :is_veteran_or_active_military => false,
          :is_vets_spouse_or_child => false},
        :attestation =>
         {:is_incarcerated => false,
          :is_self_attested_disabled => false,
          :is_self_attested_blind => false,
          :is_self_attested_long_term_care => false},
        :is_primary_applicant => true,
        :native_american_information =>
         {:indian_tribe_member => false, :tribal_name => nil, :tribal_state => nil},
        :citizenship_immigration_status_information =>
         {:citizen_status => "us_citizen",
          :is_resident_post_092296 => nil,
          :is_lawful_presence_self_attested => false},
        :is_consumer_role => true,
        :is_resident_role => false,
        :is_applying_coverage => true,
        :five_year_bar_applies => false,
        :five_year_bar_met => false,
        :qualified_non_citizen => false,
        :is_consent_applicant => false,
        :vlp_document => nil,
        :family_member_reference =>
         {:family_member_hbx_id => "200201355",
          :first_name => "adult2.1",
          :last_name => "test",
          :person_hbx_id => "200201355",
          :is_primary_family_member => true},
        :person_hbx_id => "200201355",
        :is_required_to_file_taxes => true,
        :is_filing_as_head_of_household => false,
        :tax_filer_kind => "tax_filer",
        :is_joint_tax_filing => false,
        :is_claimed_as_tax_dependent => false,
        :claimed_as_tax_dependent_by => nil,
        :student =>
         {:is_student => false,
          :student_kind => nil,
          :student_school_kind => nil,
          :student_status_end_on => nil},
        :is_refugee => false,
        :is_trafficking_victim => false,
        :foster_care =>
         {:is_former_foster_care => false,
          :age_left_foster_care => nil,
          :foster_care_us_state => nil,
          :had_medicaid_during_foster_care => false},
        :pregnancy_information =>
         {:is_pregnant => false,
          :is_enrolled_on_medicaid => false,
          :is_post_partum_period => false,
          :expected_children_count => nil,
          :pregnancy_due_on => nil,
          :pregnancy_end_on => nil},
        :is_primary_caregiver => false,
        :is_subject_to_five_year_bar => false,
        :is_five_year_bar_met => false,
        :is_forty_quarters => false,
        :is_ssn_applied => false,
        :non_ssn_apply_reason => nil,
        :moved_on_or_after_welfare_reformed_law => false,
        :is_currently_enrolled_in_health_plan => false,
        :has_daily_living_help => false,
        :need_help_paying_bills => false,
        :has_job_income => false,
        :has_self_employment_income => true,
        :has_unemployment_income => false,
        :has_other_income => false,
        :has_deductions => false,
        :has_enrolled_health_coverage => false,
        :has_eligible_health_coverage => false,
        :job_coverage_ended_in_past_3_months => false,
        :job_coverage_end_date => nil,
        :medicaid_and_chip =>
         {:not_eligible_in_last_90_days => false,
          :denied_on => nil,
          :ended_as_change_in_eligibility => false,
          :hh_income_or_size_changed => false,
          :medicaid_or_chip_coverage_end_date => nil,
          :ineligible_due_to_immigration_in_last_5_years => false,
          :immigration_status_changed_since_ineligibility => false},
        :other_health_service => {:has_received => false, :is_eligible => false},
        :addresses =>
         [{:kind => "home",
           :address_1 => "239 k",
           :address_2 => nil,
           :address_3 => nil,
           :city => "augusta",
           :county => "Cumberland",
           :state => "ME",
           :zip => "04003",
           :country_name => nil}],
        :emails => [],
        :phones => [],
        :incomes =>
         [{:title => nil,
           :kind => "net_self_employment",
           :wage_type => nil,
           :hours_per_week => nil,
           :amount => "70000.0",
           :amount_tax_exempt => "0.0",
           :frequency_kind => "Annually",
           :start_on => "2022-01-01",
           :end_on => nil,
           :is_projected => false,
           :employer => nil,
           :has_property_usage_rights => nil,
           :ssi_type => nil,
           :submitted_at => "2022-10-14T13:35:17.000+00:00"}],
        :benefits => [],
        :deductions => [],
        :is_medicare_eligible => false,
        :has_insurance => false,
        :has_state_health_benefit => false,
        :had_prior_insurance => false,
        :prior_insurance_end_date => nil,
        :age_of_applicant => 22,
        :is_self_attested_long_term_care => false,
        :hours_worked_per_week => 0,
        :is_temporarily_out_of_state => false,
        :is_claimed_as_dependent_by_non_applicant => false,
        :benchmark_premium =>
         {:health_only_lcsp_premiums =>
           [{:member_identifier => "200201355", :monthly_premium => "300.86"},
            {:member_identifier => "200201358", :monthly_premium => "230.15"},
            {:member_identifier => "200201360", :monthly_premium => "230.15"},
            {:member_identifier => "200201361", :monthly_premium => "230.15"},
            {:member_identifier => "200201362", :monthly_premium => "230.15"}],
          :health_only_slcsp_premiums =>
           [{:member_identifier => "200201355", :monthly_premium => "308.45"},
            {:member_identifier => "200201358", :monthly_premium => "235.97"},
            {:member_identifier => "200201360", :monthly_premium => "235.97"},
            {:member_identifier => "200201361", :monthly_premium => "235.97"},
            {:member_identifier => "200201362", :monthly_premium => "235.97"}]},
        :is_homeless => false,
        :mitc_income =>
         {:amount => 70_000,
          :taxable_interest => 0,
          :tax_exempt_interest => 0,
          :taxable_refunds => 0,
          :alimony => 0,
          :capital_gain_or_loss => 0,
          :pensions_and_annuities_taxable_amount => 0,
          :farm_income_or_loss => 0,
          :unemployment_compensation => 0,
          :other_income => 0,
          :magi_deductions => 0,
          :adjusted_gross_income => 70_000,
          :deductible_part_of_self_employment_tax => 0,
          :ira_deduction => 0,
          :student_loan_interest_deduction => 0,
          :tution_and_fees => 0,
          :other_magi_eligible_income => 0},
        :mitc_relationships =>
         [{:other_id => 200_201_358,
           :attest_primary_responsibility => "Y",
           :relationship_code => "03"},
          {:other_id => 200_201_360,
           :attest_primary_responsibility => "Y",
           :relationship_code => "03"},
          {:other_id => 200_201_361,
           :attest_primary_responsibility => "Y",
           :relationship_code => "03"},
          {:other_id => 200_201_362,
           :attest_primary_responsibility => "Y",
           :relationship_code => "03"}],
        :mitc_state_resident => true,
        :mitc_is_required_to_file_taxes => true,
        :income_evidence => nil,
        :esi_evidence => nil,
        :non_esi_evidence => nil,
        :local_mec_evidence => nil},
       {:name =>
         {:first_name => "childtest1",
          :middle_name => nil,
          :last_name => "test",
          :name_sfx => nil,
          :name_pfx => nil},
        :identifying_information =>
         {:encrypted_ssn => "1/WLnrxXDTUE4mi98BGIUoMFu/wGL8RNkg==\n",
          :has_ssn => false},
        :demographic =>
         {:gender => "Female",
          :dob => "2019-01-01",
          :ethnicity => [],
          :race => nil,
          :is_veteran_or_active_military => false,
          :is_vets_spouse_or_child => false},
        :attestation =>
         {:is_incarcerated => false,
          :is_self_attested_disabled => false,
          :is_self_attested_blind => false,
          :is_self_attested_long_term_care => false},
        :is_primary_applicant => false,
        :native_american_information =>
         {:indian_tribe_member => false, :tribal_name => nil, :tribal_state => nil},
        :citizenship_immigration_status_information =>
         {:citizen_status => "us_citizen",
          :is_resident_post_092296 => nil,
          :is_lawful_presence_self_attested => false},
        :is_consumer_role => true,
        :is_resident_role => false,
        :is_applying_coverage => true,
        :five_year_bar_applies => false,
        :five_year_bar_met => false,
        :qualified_non_citizen => false,
        :is_consent_applicant => false,
        :vlp_document => nil,
        :family_member_reference =>
         {:family_member_hbx_id => "200201358",
          :first_name => "childtest1",
          :last_name => "test",
          :person_hbx_id => "200201358",
          :is_primary_family_member => false},
        :person_hbx_id => "200201358",
        :is_required_to_file_taxes => false,
        :is_filing_as_head_of_household => false,
        :tax_filer_kind => "dependent",
        :is_joint_tax_filing => false,
        :is_claimed_as_tax_dependent => true,
        :claimed_as_tax_dependent_by =>
         {:first_name => "adult2.1",
          :last_name => "test",
          :dob => "2000-01-01",
          :person_hbx_id => "200201355",
          :encrypted_ssn => "qfl5FpLXZtCR5omSMxhi6IMGvP8HLMVJlA==\n"},
        :student =>
         {:is_student => false,
          :student_kind => nil,
          :student_school_kind => nil,
          :student_status_end_on => nil},
        :is_refugee => false,
        :is_trafficking_victim => false,
        :foster_care =>
         {:is_former_foster_care => false,
          :age_left_foster_care => nil,
          :foster_care_us_state => nil,
          :had_medicaid_during_foster_care => false},
        :pregnancy_information =>
         {:is_pregnant => false,
          :is_enrolled_on_medicaid => false,
          :is_post_partum_period => false,
          :expected_children_count => nil,
          :pregnancy_due_on => nil,
          :pregnancy_end_on => nil},
        :is_primary_caregiver => nil,
        :is_subject_to_five_year_bar => false,
        :is_five_year_bar_met => false,
        :is_forty_quarters => false,
        :is_ssn_applied => false,
        :non_ssn_apply_reason => nil,
        :moved_on_or_after_welfare_reformed_law => false,
        :is_currently_enrolled_in_health_plan => false,
        :has_daily_living_help => false,
        :need_help_paying_bills => false,
        :has_job_income => false,
        :has_self_employment_income => false,
        :has_unemployment_income => false,
        :has_other_income => false,
        :has_deductions => false,
        :has_enrolled_health_coverage => false,
        :has_eligible_health_coverage => false,
        :job_coverage_ended_in_past_3_months => false,
        :job_coverage_end_date => nil,
        :medicaid_and_chip =>
         {:not_eligible_in_last_90_days => false,
          :denied_on => nil,
          :ended_as_change_in_eligibility => false,
          :hh_income_or_size_changed => false,
          :medicaid_or_chip_coverage_end_date => nil,
          :ineligible_due_to_immigration_in_last_5_years => false,
          :immigration_status_changed_since_ineligibility => false},
        :other_health_service => {:has_received => false, :is_eligible => false},
        :addresses =>
         [{:kind => "home",
           :address_1 => "239 k",
           :address_2 => nil,
           :address_3 => nil,
           :city => "augusta",
           :county => "Cumberland",
           :state => "ME",
           :zip => "04003",
           :country_name => nil}],
        :emails => [],
        :phones => [],
        :incomes => [],
        :benefits => [],
        :deductions => [],
        :is_medicare_eligible => false,
        :has_insurance => false,
        :has_state_health_benefit => false,
        :had_prior_insurance => false,
        :prior_insurance_end_date => nil,
        :age_of_applicant => 3,
        :is_self_attested_long_term_care => false,
        :hours_worked_per_week => 0,
        :is_temporarily_out_of_state => false,
        :is_claimed_as_dependent_by_non_applicant => false,
        :benchmark_premium =>
         {:health_only_lcsp_premiums =>
           [{:member_identifier => "200201355", :monthly_premium => "300.86"},
            {:member_identifier => "200201358", :monthly_premium => "230.15"},
            {:member_identifier => "200201360", :monthly_premium => "230.15"},
            {:member_identifier => "200201361", :monthly_premium => "230.15"},
            {:member_identifier => "200201362", :monthly_premium => "230.15"}],
          :health_only_slcsp_premiums =>
           [{:member_identifier => "200201355", :monthly_premium => "308.45"},
            {:member_identifier => "200201358", :monthly_premium => "235.97"},
            {:member_identifier => "200201360", :monthly_premium => "235.97"},
            {:member_identifier => "200201361", :monthly_premium => "235.97"},
            {:member_identifier => "200201362", :monthly_premium => "235.97"}]},
        :is_homeless => false,
        :mitc_income =>
         {:amount => 0,
          :taxable_interest => 0,
          :tax_exempt_interest => 0,
          :taxable_refunds => 0,
          :alimony => 0,
          :capital_gain_or_loss => 0,
          :pensions_and_annuities_taxable_amount => 0,
          :farm_income_or_loss => 0,
          :unemployment_compensation => 0,
          :other_income => 0,
          :magi_deductions => 0,
          :adjusted_gross_income => 0,
          :deductible_part_of_self_employment_tax => 0,
          :ira_deduction => 0,
          :student_loan_interest_deduction => 0,
          :tution_and_fees => 0,
          :other_magi_eligible_income => 0},
        :mitc_relationships =>
         [{:other_id => 200_201_355,
           :attest_primary_responsibility => "N",
           :relationship_code => "04"},
          {:other_id => 200_201_360,
           :attest_primary_responsibility => "N",
           :relationship_code => "07"},
          {:other_id => 200_201_361,
           :attest_primary_responsibility => "N",
           :relationship_code => "07"},
          {:other_id => 200_201_362,
           :attest_primary_responsibility => "N",
           :relationship_code => "07"}],
        :mitc_state_resident => true,
        :mitc_is_required_to_file_taxes => false,
        :income_evidence => nil,
        :esi_evidence => nil,
        :non_esi_evidence => nil,
        :local_mec_evidence => nil},
       {:name =>
         {:first_name => "childtest2",
          :middle_name => nil,
          :last_name => "test",
          :name_sfx => nil,
          :name_pfx => nil},
        :identifying_information =>
         {:encrypted_ssn => "hsytIzg+XFT+SPvdinpoEYMHvvwGL8JLkw==\n",
          :has_ssn => false},
        :demographic =>
         {:gender => "Male",
          :dob => "2020-01-01",
          :ethnicity => [],
          :race => nil,
          :is_veteran_or_active_military => false,
          :is_vets_spouse_or_child => false},
        :attestation =>
         {:is_incarcerated => false,
          :is_self_attested_disabled => false,
          :is_self_attested_blind => false,
          :is_self_attested_long_term_care => false},
        :is_primary_applicant => false,
        :native_american_information =>
         {:indian_tribe_member => false, :tribal_name => nil, :tribal_state => nil},
        :citizenship_immigration_status_information =>
         {:citizen_status => "us_citizen",
          :is_resident_post_092296 => nil,
          :is_lawful_presence_self_attested => false},
        :is_consumer_role => true,
        :is_resident_role => false,
        :is_applying_coverage => true,
        :five_year_bar_applies => false,
        :five_year_bar_met => false,
        :qualified_non_citizen => false,
        :is_consent_applicant => false,
        :vlp_document => nil,
        :family_member_reference =>
         {:family_member_hbx_id => "200201360",
          :first_name => "childtest2",
          :last_name => "test",
          :person_hbx_id => "200201360",
          :is_primary_family_member => false},
        :person_hbx_id => "200201360",
        :is_required_to_file_taxes => false,
        :is_filing_as_head_of_household => false,
        :tax_filer_kind => "dependent",
        :is_joint_tax_filing => false,
        :is_claimed_as_tax_dependent => true,
        :claimed_as_tax_dependent_by =>
         {:first_name => "adult2.1",
          :last_name => "test",
          :dob => "2000-01-01",
          :person_hbx_id => "200201355",
          :encrypted_ssn => "qfl5FpLXZtCR5omSMxhi6IMGvP8HLMVJlA==\n"},
        :student =>
         {:is_student => false,
          :student_kind => nil,
          :student_school_kind => nil,
          :student_status_end_on => nil},
        :is_refugee => false,
        :is_trafficking_victim => false,
        :foster_care =>
         {:is_former_foster_care => false,
          :age_left_foster_care => nil,
          :foster_care_us_state => nil,
          :had_medicaid_during_foster_care => false},
        :pregnancy_information =>
         {:is_pregnant => false,
          :is_enrolled_on_medicaid => false,
          :is_post_partum_period => false,
          :expected_children_count => nil,
          :pregnancy_due_on => nil,
          :pregnancy_end_on => nil},
        :is_primary_caregiver => nil,
        :is_subject_to_five_year_bar => false,
        :is_five_year_bar_met => false,
        :is_forty_quarters => false,
        :is_ssn_applied => false,
        :non_ssn_apply_reason => nil,
        :moved_on_or_after_welfare_reformed_law => false,
        :is_currently_enrolled_in_health_plan => false,
        :has_daily_living_help => false,
        :need_help_paying_bills => false,
        :has_job_income => false,
        :has_self_employment_income => false,
        :has_unemployment_income => false,
        :has_other_income => false,
        :has_deductions => false,
        :has_enrolled_health_coverage => false,
        :has_eligible_health_coverage => false,
        :job_coverage_ended_in_past_3_months => false,
        :job_coverage_end_date => nil,
        :medicaid_and_chip =>
         {:not_eligible_in_last_90_days => false,
          :denied_on => nil,
          :ended_as_change_in_eligibility => false,
          :hh_income_or_size_changed => false,
          :medicaid_or_chip_coverage_end_date => nil,
          :ineligible_due_to_immigration_in_last_5_years => false,
          :immigration_status_changed_since_ineligibility => false},
        :other_health_service => {:has_received => false, :is_eligible => false},
        :addresses =>
         [{:kind => "home",
           :address_1 => "239 k",
           :address_2 => nil,
           :address_3 => nil,
           :city => "augusta",
           :county => "Cumberland",
           :state => "ME",
           :zip => "04003",
           :country_name => nil}],
        :emails => [],
        :phones => [],
        :incomes => [],
        :benefits => [],
        :deductions => [],
        :is_medicare_eligible => false,
        :has_insurance => false,
        :has_state_health_benefit => false,
        :had_prior_insurance => false,
        :prior_insurance_end_date => nil,
        :age_of_applicant => 2,
        :is_self_attested_long_term_care => false,
        :hours_worked_per_week => 0,
        :is_temporarily_out_of_state => false,
        :is_claimed_as_dependent_by_non_applicant => false,
        :benchmark_premium =>
         {:health_only_lcsp_premiums =>
           [{:member_identifier => "200201355", :monthly_premium => "300.86"},
            {:member_identifier => "200201358", :monthly_premium => "230.15"},
            {:member_identifier => "200201360", :monthly_premium => "230.15"},
            {:member_identifier => "200201361", :monthly_premium => "230.15"},
            {:member_identifier => "200201362", :monthly_premium => "230.15"}],
          :health_only_slcsp_premiums =>
           [{:member_identifier => "200201355", :monthly_premium => "308.45"},
            {:member_identifier => "200201358", :monthly_premium => "235.97"},
            {:member_identifier => "200201360", :monthly_premium => "235.97"},
            {:member_identifier => "200201361", :monthly_premium => "235.97"},
            {:member_identifier => "200201362", :monthly_premium => "235.97"}]},
        :is_homeless => false,
        :mitc_income =>
         {:amount => 0,
          :taxable_interest => 0,
          :tax_exempt_interest => 0,
          :taxable_refunds => 0,
          :alimony => 0,
          :capital_gain_or_loss => 0,
          :pensions_and_annuities_taxable_amount => 0,
          :farm_income_or_loss => 0,
          :unemployment_compensation => 0,
          :other_income => 0,
          :magi_deductions => 0,
          :adjusted_gross_income => 0,
          :deductible_part_of_self_employment_tax => 0,
          :ira_deduction => 0,
          :student_loan_interest_deduction => 0,
          :tution_and_fees => 0,
          :other_magi_eligible_income => 0},
        :mitc_relationships =>
         [{:other_id => 200_201_355,
           :attest_primary_responsibility => "N",
           :relationship_code => "04"},
          {:other_id => 200_201_358,
           :attest_primary_responsibility => "N",
           :relationship_code => "07"},
          {:other_id => 200_201_361,
           :attest_primary_responsibility => "N",
           :relationship_code => "07"},
          {:other_id => 200_201_362,
           :attest_primary_responsibility => "N",
           :relationship_code => "07"}],
        :mitc_state_resident => true,
        :mitc_is_required_to_file_taxes => false,
        :income_evidence => nil,
        :esi_evidence => nil,
        :non_esi_evidence => nil,
        :local_mec_evidence => nil},
       {:name =>
         {:first_name => "childtest3",
          :middle_name => nil,
          :last_name => "test",
          :name_sfx => nil,
          :name_pfx => nil},
        :identifying_information =>
         {:encrypted_ssn => "fakBWDUfwvztdoXP5kINVoMAvf0FLcVIkw==\n",
          :has_ssn => false},
        :demographic =>
         {:gender => "Male",
          :dob => "2021-01-01",
          :ethnicity => [],
          :race => nil,
          :is_veteran_or_active_military => false,
          :is_vets_spouse_or_child => false},
        :attestation =>
         {:is_incarcerated => false,
          :is_self_attested_disabled => false,
          :is_self_attested_blind => false,
          :is_self_attested_long_term_care => false},
        :is_primary_applicant => false,
        :native_american_information =>
         {:indian_tribe_member => false, :tribal_name => nil, :tribal_state => nil},
        :citizenship_immigration_status_information =>
         {:citizen_status => "us_citizen",
          :is_resident_post_092296 => nil,
          :is_lawful_presence_self_attested => false},
        :is_consumer_role => true,
        :is_resident_role => false,
        :is_applying_coverage => true,
        :five_year_bar_applies => false,
        :five_year_bar_met => false,
        :qualified_non_citizen => false,
        :is_consent_applicant => false,
        :vlp_document => nil,
        :family_member_reference =>
         {:family_member_hbx_id => "200201361",
          :first_name => "childtest3",
          :last_name => "test",
          :person_hbx_id => "200201361",
          :is_primary_family_member => false},
        :person_hbx_id => "200201361",
        :is_required_to_file_taxes => false,
        :is_filing_as_head_of_household => false,
        :tax_filer_kind => "dependent",
        :is_joint_tax_filing => false,
        :is_claimed_as_tax_dependent => true,
        :claimed_as_tax_dependent_by =>
         {:first_name => "adult2.1",
          :last_name => "test",
          :dob => "2000-01-01",
          :person_hbx_id => "200201355",
          :encrypted_ssn => "qfl5FpLXZtCR5omSMxhi6IMGvP8HLMVJlA==\n"},
        :student =>
         {:is_student => false,
          :student_kind => nil,
          :student_school_kind => nil,
          :student_status_end_on => nil},
        :is_refugee => false,
        :is_trafficking_victim => false,
        :foster_care =>
         {:is_former_foster_care => false,
          :age_left_foster_care => nil,
          :foster_care_us_state => nil,
          :had_medicaid_during_foster_care => false},
        :pregnancy_information =>
         {:is_pregnant => false,
          :is_enrolled_on_medicaid => false,
          :is_post_partum_period => false,
          :expected_children_count => nil,
          :pregnancy_due_on => nil,
          :pregnancy_end_on => nil},
        :is_primary_caregiver => nil,
        :is_subject_to_five_year_bar => false,
        :is_five_year_bar_met => false,
        :is_forty_quarters => false,
        :is_ssn_applied => false,
        :non_ssn_apply_reason => nil,
        :moved_on_or_after_welfare_reformed_law => false,
        :is_currently_enrolled_in_health_plan => false,
        :has_daily_living_help => false,
        :need_help_paying_bills => false,
        :has_job_income => false,
        :has_self_employment_income => false,
        :has_unemployment_income => false,
        :has_other_income => false,
        :has_deductions => false,
        :has_enrolled_health_coverage => false,
        :has_eligible_health_coverage => false,
        :job_coverage_ended_in_past_3_months => false,
        :job_coverage_end_date => nil,
        :medicaid_and_chip =>
         {:not_eligible_in_last_90_days => false,
          :denied_on => nil,
          :ended_as_change_in_eligibility => false,
          :hh_income_or_size_changed => false,
          :medicaid_or_chip_coverage_end_date => nil,
          :ineligible_due_to_immigration_in_last_5_years => false,
          :immigration_status_changed_since_ineligibility => false},
        :other_health_service => {:has_received => false, :is_eligible => false},
        :addresses =>
         [{:kind => "home",
           :address_1 => "239 k",
           :address_2 => nil,
           :address_3 => nil,
           :city => "augusta",
           :county => "Cumberland",
           :state => "ME",
           :zip => "04003",
           :country_name => nil}],
        :emails => [],
        :phones => [],
        :incomes => [],
        :benefits => [],
        :deductions => [],
        :is_medicare_eligible => false,
        :has_insurance => false,
        :has_state_health_benefit => false,
        :had_prior_insurance => false,
        :prior_insurance_end_date => nil,
        :age_of_applicant => 1,
        :is_self_attested_long_term_care => false,
        :hours_worked_per_week => 0,
        :is_temporarily_out_of_state => false,
        :is_claimed_as_dependent_by_non_applicant => false,
        :benchmark_premium =>
         {:health_only_lcsp_premiums =>
           [{:member_identifier => "200201355", :monthly_premium => "300.86"},
            {:member_identifier => "200201358", :monthly_premium => "230.15"},
            {:member_identifier => "200201360", :monthly_premium => "230.15"},
            {:member_identifier => "200201361", :monthly_premium => "230.15"},
            {:member_identifier => "200201362", :monthly_premium => "230.15"}],
          :health_only_slcsp_premiums =>
           [{:member_identifier => "200201355", :monthly_premium => "308.45"},
            {:member_identifier => "200201358", :monthly_premium => "235.97"},
            {:member_identifier => "200201360", :monthly_premium => "235.97"},
            {:member_identifier => "200201361", :monthly_premium => "235.97"},
            {:member_identifier => "200201362", :monthly_premium => "235.97"}]},
        :is_homeless => false,
        :mitc_income =>
         {:amount => 0,
          :taxable_interest => 0,
          :tax_exempt_interest => 0,
          :taxable_refunds => 0,
          :alimony => 0,
          :capital_gain_or_loss => 0,
          :pensions_and_annuities_taxable_amount => 0,
          :farm_income_or_loss => 0,
          :unemployment_compensation => 0,
          :other_income => 0,
          :magi_deductions => 0,
          :adjusted_gross_income => 0,
          :deductible_part_of_self_employment_tax => 0,
          :ira_deduction => 0,
          :student_loan_interest_deduction => 0,
          :tution_and_fees => 0,
          :other_magi_eligible_income => 0},
        :mitc_relationships =>
         [{:other_id => 200_201_355,
           :attest_primary_responsibility => "N",
           :relationship_code => "04"},
          {:other_id => 200_201_358,
           :attest_primary_responsibility => "N",
           :relationship_code => "07"},
          {:other_id => 200_201_360,
           :attest_primary_responsibility => "N",
           :relationship_code => "07"},
          {:other_id => 200_201_362,
           :attest_primary_responsibility => "N",
           :relationship_code => "07"}],
        :mitc_state_resident => true,
        :mitc_is_required_to_file_taxes => false,
        :income_evidence => nil,
        :esi_evidence => nil,
        :non_esi_evidence => nil,
        :local_mec_evidence => nil},
       {:name =>
         {:first_name => "childtest4",
          :middle_name => nil,
          :last_name => "test",
          :name_sfx => nil,
          :name_pfx => nil},
        :identifying_information =>
         {:encrypted_ssn => "Stc/ycLO5WsL+M99+beqgIMFvv0EL8ZKkA==\n",
          :has_ssn => false},
        :demographic =>
         {:gender => "Female",
          :dob => "2021-01-01",
          :ethnicity => [],
          :race => nil,
          :is_veteran_or_active_military => false,
          :is_vets_spouse_or_child => false},
        :attestation =>
         {:is_incarcerated => false,
          :is_self_attested_disabled => false,
          :is_self_attested_blind => false,
          :is_self_attested_long_term_care => false},
        :is_primary_applicant => false,
        :native_american_information =>
         {:indian_tribe_member => false, :tribal_name => nil, :tribal_state => nil},
        :citizenship_immigration_status_information =>
         {:citizen_status => "us_citizen",
          :is_resident_post_092296 => nil,
          :is_lawful_presence_self_attested => false},
        :is_consumer_role => true,
        :is_resident_role => false,
        :is_applying_coverage => true,
        :five_year_bar_applies => false,
        :five_year_bar_met => false,
        :qualified_non_citizen => false,
        :is_consent_applicant => false,
        :vlp_document => nil,
        :family_member_reference =>
         {:family_member_hbx_id => "200201362",
          :first_name => "childtest4",
          :last_name => "test",
          :person_hbx_id => "200201362",
          :is_primary_family_member => false},
        :person_hbx_id => "200201362",
        :is_required_to_file_taxes => false,
        :is_filing_as_head_of_household => false,
        :tax_filer_kind => "dependent",
        :is_joint_tax_filing => false,
        :is_claimed_as_tax_dependent => true,
        :claimed_as_tax_dependent_by =>
         {:first_name => "adult2.1",
          :last_name => "test",
          :dob => "2000-01-01",
          :person_hbx_id => "200201355",
          :encrypted_ssn => "qfl5FpLXZtCR5omSMxhi6IMGvP8HLMVJlA==\n"},
        :student =>
         {:is_student => false,
          :student_kind => nil,
          :student_school_kind => nil,
          :student_status_end_on => nil},
        :is_refugee => false,
        :is_trafficking_victim => false,
        :foster_care =>
         {:is_former_foster_care => false,
          :age_left_foster_care => nil,
          :foster_care_us_state => nil,
          :had_medicaid_during_foster_care => false},
        :pregnancy_information =>
         {:is_pregnant => false,
          :is_enrolled_on_medicaid => false,
          :is_post_partum_period => false,
          :expected_children_count => nil,
          :pregnancy_due_on => nil,
          :pregnancy_end_on => nil},
        :is_primary_caregiver => nil,
        :is_subject_to_five_year_bar => false,
        :is_five_year_bar_met => false,
        :is_forty_quarters => false,
        :is_ssn_applied => false,
        :non_ssn_apply_reason => nil,
        :moved_on_or_after_welfare_reformed_law => false,
        :is_currently_enrolled_in_health_plan => false,
        :has_daily_living_help => false,
        :need_help_paying_bills => false,
        :has_job_income => false,
        :has_self_employment_income => false,
        :has_unemployment_income => false,
        :has_other_income => false,
        :has_deductions => false,
        :has_enrolled_health_coverage => false,
        :has_eligible_health_coverage => false,
        :job_coverage_ended_in_past_3_months => false,
        :job_coverage_end_date => nil,
        :medicaid_and_chip =>
         {:not_eligible_in_last_90_days => false,
          :denied_on => nil,
          :ended_as_change_in_eligibility => false,
          :hh_income_or_size_changed => false,
          :medicaid_or_chip_coverage_end_date => nil,
          :ineligible_due_to_immigration_in_last_5_years => false,
          :immigration_status_changed_since_ineligibility => false},
        :other_health_service => {:has_received => false, :is_eligible => false},
        :addresses =>
         [{:kind => "home",
           :address_1 => "239 k",
           :address_2 => nil,
           :address_3 => nil,
           :city => "augusta",
           :county => "Cumberland",
           :state => "ME",
           :zip => "04003",
           :country_name => nil}],
        :emails => [],
        :phones => [],
        :incomes => [],
        :benefits => [],
        :deductions => [],
        :is_medicare_eligible => false,
        :has_insurance => false,
        :has_state_health_benefit => false,
        :had_prior_insurance => false,
        :prior_insurance_end_date => nil,
        :age_of_applicant => 1,
        :is_self_attested_long_term_care => false,
        :hours_worked_per_week => 0,
        :is_temporarily_out_of_state => false,
        :is_claimed_as_dependent_by_non_applicant => false,
        :benchmark_premium =>
         {:health_only_lcsp_premiums =>
           [{:member_identifier => "200201355", :monthly_premium => "300.86"},
            {:member_identifier => "200201358", :monthly_premium => "230.15"},
            {:member_identifier => "200201360", :monthly_premium => "230.15"},
            {:member_identifier => "200201361", :monthly_premium => "230.15"},
            {:member_identifier => "200201362", :monthly_premium => "230.15"}],
          :health_only_slcsp_premiums =>
           [{:member_identifier => "200201355", :monthly_premium => "308.45"},
            {:member_identifier => "200201358", :monthly_premium => "235.97"},
            {:member_identifier => "200201360", :monthly_premium => "235.97"},
            {:member_identifier => "200201361", :monthly_premium => "235.97"},
            {:member_identifier => "200201362", :monthly_premium => "235.97"}]},
        :is_homeless => false,
        :mitc_income =>
         {:amount => 0,
          :taxable_interest => 0,
          :tax_exempt_interest => 0,
          :taxable_refunds => 0,
          :alimony => 0,
          :capital_gain_or_loss => 0,
          :pensions_and_annuities_taxable_amount => 0,
          :farm_income_or_loss => 0,
          :unemployment_compensation => 0,
          :other_income => 0,
          :magi_deductions => 0,
          :adjusted_gross_income => 0,
          :deductible_part_of_self_employment_tax => 0,
          :ira_deduction => 0,
          :student_loan_interest_deduction => 0,
          :tution_and_fees => 0,
          :other_magi_eligible_income => 0},
        :mitc_relationships =>
         [{:other_id => 200_201_355,
           :attest_primary_responsibility => "N",
           :relationship_code => "04"},
          {:other_id => 200_201_358,
           :attest_primary_responsibility => "N",
           :relationship_code => "07"},
          {:other_id => 200_201_360,
           :attest_primary_responsibility => "N",
           :relationship_code => "07"},
          {:other_id => 200_201_361,
           :attest_primary_responsibility => "N",
           :relationship_code => "07"}],
        :mitc_state_resident => true,
        :mitc_is_required_to_file_taxes => false,
        :income_evidence => nil,
        :esi_evidence => nil,
        :non_esi_evidence => nil,
        :local_mec_evidence => nil}],
     :tax_households =>
      [{:max_aptc => "840.0",
        :hbx_id => "118825",
        :is_insurance_assistance_eligible => "Yes",
        :tax_household_members =>
         [{:product_eligibility_determination =>
            {:is_ia_eligible => true,
             :is_medicaid_chip_eligible => false,
             :is_totally_ineligible => nil,
             :is_magi_medicaid => false,
             :is_uqhp_eligible => nil,
             :is_csr_eligible => true,
             :csr => "73",
             :is_non_magi_medicaid_eligible => false,
             :is_without_assistance => false,
             :magi_medicaid_monthly_household_income => "70000.0",
             :medicaid_household_size => 5,
             :magi_medicaid_monthly_income_limit => "0.0",
             :magi_as_percentage_of_fpl => "215.0",
             :magi_medicaid_category => "adult_group",
             :magi_medicaid_ineligibility_reasons =>
              ["Applicant's MAGI above the threshold for category"],
             :is_eligible_for_non_magi_reasons => false,
             :chip_ineligibility_reasons =>
              ["Applicant did not meet the requirements for any CHIP category"],
             :magi_medicaid_category_threshold => "44808.0",
             :medicaid_chip_category => "None",
             :medicaid_chip_category_threshold => "0.0",
             :category_determinations =>
              [{:category => "Residency",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Adult Group Category",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Parent Caretaker Category",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Pregnancy Category",
                :indicator_code => false,
                :ineligibility_code => 124,
                :ineligibility_reason =>
                 "Applicant not pregnant or within postpartum period"},
               {:category => "Child Category",
                :indicator_code => false,
                :ineligibility_code => 394,
                :ineligibility_reason =>
                 "Applicant is over theage limit for the young adult threshold in the state"},
               {:category => "Optional Targeted Low Income Child",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "CHIP Targeted Low Income Child",
                :indicator_code => false,
                :ineligibility_code => 127,
                :ineligibility_reason =>
                 "Applicant's age is not within the allowed age range"},
               {:category => "Unborn Child",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Income Medicaid Eligible",
                :indicator_code => false,
                :ineligibility_code => 402,
                :ineligibility_reason =>
                 "Applicant's income is greater than the threshold for all eligible categories"},
               {:category => "Income CHIP Eligible",
                :indicator_code => false,
                :ineligibility_code => 401,
                :ineligibility_reason =>
                 "Applicant did not meet the requirements for any eligibility category"},
               {:category => "Medicaid CHIPRA 214",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "CHIP CHIPRA 214",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Trafficking Victim",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Seven Year Limit",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Five Year Bar",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Title II Work Quarters Met",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Medicaid Citizen Or Immigrant",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "CHIP Citizen Or Immigrant",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Former Foster Care Category",
                :indicator_code => false,
                :ineligibility_code => 400,
                :ineligibility_reason =>
                 "Applicant was not formerly in foster care"},
               {:category => "Work Quarters Override Income",
                :indicator_code => false,
                :ineligibility_code => 340,
                :ineligibility_reason => "Income is greater than 100% FPL"},
               {:category => "State Health Benefits CHIP",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "CHIP Waiting Period Satisfied",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Dependent Child Covered",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Medicaid Non-MAGI Referral",
                :indicator_code => false,
                :ineligibility_code => 108,
                :ineligibility_reason =>
                 "Applicant does not meet requirements for a non-MAGI referral"},
               {:category => "Emergency Medicaid",
                :indicator_code => false,
                :ineligibility_code => 109,
                :ineligibility_reason =>
                 "Applicant does not meet themeligibility criteria for emergency Medicaid"},
               {:category => "Refugee Medical Assistance",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "APTC Referral",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil}]},
           :applicant_reference =>
            {:first_name => "adult2.1",
             :last_name => "test",
             :dob => "2000-01-01",
             :person_hbx_id => "200201355",
             :encrypted_ssn => "qfl5FpLXZtCR5omSMxhi6IMGvP8HLMVJlA==\n"}},
          {:product_eligibility_determination =>
            {:is_ia_eligible => true,
             :is_medicaid_chip_eligible => false,
             :is_totally_ineligible => nil,
             :is_magi_medicaid => false,
             :is_uqhp_eligible => nil,
             :is_csr_eligible => true,
             :csr => "73",
             :is_non_magi_medicaid_eligible => false,
             :is_without_assistance => false,
             :magi_medicaid_monthly_household_income => "70000.0",
             :medicaid_household_size => 5,
             :magi_medicaid_monthly_income_limit => "0.0",
             :magi_as_percentage_of_fpl => "215.0",
             :magi_medicaid_category => "child",
             :magi_medicaid_ineligibility_reasons =>
              ["Applicant's MAGI above the threshold for category"],
             :is_eligible_for_non_magi_reasons => false,
             :chip_ineligibility_reasons =>
              ["Applicant's MAGI above the threshold for category"],
             :magi_medicaid_category_threshold => "52601.0",
             :medicaid_chip_category => "CHIP Targeted Low Income Child",
             :medicaid_chip_category_threshold => "69161.0",
             :category_determinations =>
              [{:category => "Residency",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Adult Group Category",
                :indicator_code => false,
                :ineligibility_code => 123,
                :ineligibility_reason =>
                 "Applicant is not between the ages of 19 and 64 (inclusive)"},
               {:category => "Parent Caretaker Category",
                :indicator_code => false,
                :ineligibility_code => 146,
                :ineligibility_reason =>
                 "No child met all criteria for parent caretaker category"},
               {:category => "Pregnancy Category",
                :indicator_code => false,
                :ineligibility_code => 124,
                :ineligibility_reason =>
                 "Applicant not pregnant or within postpartum period"},
               {:category => "Child Category",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Optional Targeted Low Income Child",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "CHIP Targeted Low Income Child",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Unborn Child",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Income Medicaid Eligible",
                :indicator_code => false,
                :ineligibility_code => 402,
                :ineligibility_reason =>
                 "Applicant's income is greater than the thresholdfor all eligible categories"},
               {:category => "Income CHIP Eligible",
                :indicator_code => false,
                :ineligibility_code => 402,
                :ineligibility_reason =>
                 "Applicant's income is greaterthan the threshold for all eligible categories"},
               {:category => "Medicaid CHIPRA 214",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "CHIP CHIPRA 214",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Trafficking Victim",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Seven Year Limit",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Five Year Bar",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Title II Work Quarters Met",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Medicaid Citizen Or Immigrant",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "CHIP Citizen Or Immigrant",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Former Foster Care Category",
                :indicator_code => false,
                :ineligibility_code => 400,
                :ineligibility_reason =>
                 "Applicant was not formerly in foster care"},
               {:category => "Work Quarters Override Income",
                :indicator_code => false,
                :ineligibility_code => 340,
                :ineligibility_reason => "Income is greater than 100% FPL"},
               {:category => "State Health Benefits CHIP",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "CHIP Waiting Period Satisfied",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Dependent Child Covered",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Medicaid Non-MAGI Referral",
                :indicator_code => false,
                :ineligibility_code => 108,
                :ineligibility_reason =>
                 "Applicant does not meet requirements for a non-MAGI referral"},
               {:category => "Emergency Medicaid",
                :indicator_code => false,
                :ineligibility_code => 109,
                :ineligibility_reason =>
                 "Applicant does not meet the eligibility criteria for emergency Medicaid"},
               {:category => "Refugee Medical Assistance",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "APTC Referral",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil}]},
           :applicant_reference =>
            {:first_name => "childtest1",
             :last_name => "test",
             :dob => "2019-01-01",
             :person_hbx_id => "200201358",
             :encrypted_ssn => "1/WLnrxXDTUE4mi98BGIUoMFu/wGL8RNkg==\n"}},
          {:product_eligibility_determination =>
            {:is_ia_eligible => true,
             :is_medicaid_chip_eligible => false,
             :is_totally_ineligible => nil,
             :is_magi_medicaid => false,
             :is_uqhp_eligible => nil,
             :is_csr_eligible => true,
             :csr => "73",
             :is_non_magi_medicaid_eligible => false,
             :is_without_assistance => false,
             :magi_medicaid_monthly_household_income => "70000.0",
             :medicaid_household_size => 5,
             :magi_medicaid_monthly_income_limit => "0.0",
             :magi_as_percentage_of_fpl => "215.0",
             :magi_medicaid_category => "child",
             :magi_medicaid_ineligibility_reasons =>
              ["Applicant's MAGI above the threshold for category"],
             :is_eligible_for_non_magi_reasons => false,
             :chip_ineligibility_reasons =>
              ["Applicant's MAGI above the threshold for category"],
             :magi_medicaid_category_threshold => "52601.0",
             :medicaid_chip_category => "CHIP Targeted Low Income Child",
             :medicaid_chip_category_threshold => "69161.0",
             :category_determinations =>
              [{:category => "Residency",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Adult Group Category",
                :indicator_code => false,
                :ineligibility_code => 123,
                :ineligibility_reason =>
                 "Applicant is not between the ages of 19 and 64 (inclusive)"},
               {:category => "Parent Caretaker Category",
                :indicator_code => false,
                :ineligibility_code => 146,
                :ineligibility_reason =>
                 "No child met all criteria for parent caretaker category"},
               {:category => "Pregnancy Category",
                :indicator_code => false,
                :ineligibility_code => 124,
                :ineligibility_reason =>
                 "Applicant not pregnant or within postpartum period"},
               {:category => "Child Category",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Optional Targeted Low Income Child",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "CHIP Targeted Low Income Child",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Unborn Child",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Income Medicaid Eligible",
                :indicator_code => false,
                :ineligibility_code => 402,
                :ineligibility_reason =>
                 "Applicant's income is greater than the threshold for all eligible categories"},
               {:category => "Income CHIP Eligible",
                :indicator_code => false,
                :ineligibility_code => 402,
                :ineligibility_reason =>
                 "Applicant's income is greater than the threshold for all eligible categories"},
               {:category => "Medicaid CHIPRA 214",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "CHIP CHIPRA 214",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Trafficking Victim",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Seven Year Limit",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Five Year Bar",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Title II Work Quarters Met",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Medicaid Citizen Or Immigrant",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "CHIP Citizen Or Immigrant",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Former Foster Care Category",
                :indicator_code => false,
                :ineligibility_code => 400,
                :ineligibility_reason =>
                 "Applicant was not formerly in foster care"},
               {:category => "Work Quarters Override Income",
                :indicator_code => false,
                :ineligibility_code => 340,
                :ineligibility_reason => "Income is greater than 100% FPL"},
               {:category => "State Health Benefits CHIP",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "CHIP Waiting Period Satisfied",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Dependent Child Covered",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Medicaid Non-MAGI Referral",
                :indicator_code => false,
                :ineligibility_code => 108,
                :ineligibility_reason =>
                 "Applicant does not meet requirements for a non-MAGI referral"},
               {:category => "Emergency Medicaid",
                :indicator_code => false,
                :ineligibility_code => 109,
                :ineligibility_reason =>
                 "Applicant does not meet the eligibility criteria for emergency Medicaid"},
               {:category => "Refugee Medical Assistance",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "APTC Referral",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil}]},
           :applicant_reference =>
            {:first_name => "childtest2",
             :last_name => "test",
             :dob => "2020-01-01",
             :person_hbx_id => "200201360",
             :encrypted_ssn => "hsytIzg+XFT+SPvdinpoEYMHvvwGL8JLkw==\n"}},
          {:product_eligibility_determination =>
            {:is_ia_eligible => true,
             :is_medicaid_chip_eligible => false,
             :is_totally_ineligible => nil,
             :is_magi_medicaid => false,
             :is_uqhp_eligible => nil,
             :is_csr_eligible => true,
             :csr => "73",
             :is_non_magi_medicaid_eligible => false,
             :is_without_assistance => false,
             :magi_medicaid_monthly_household_income => "70000.0",
             :medicaid_household_size => 5,
             :magi_medicaid_monthly_income_limit => "0.0",
             :magi_as_percentage_of_fpl => "215.0",
             :magi_medicaid_category => "child",
             :magi_medicaid_ineligibility_reasons =>
              ["Applicant's MAGI above the threshold for category"],
             :is_eligible_for_non_magi_reasons => false,
             :chip_ineligibility_reasons =>
              ["Applicant's MAGI above the threshold for category"],
             :magi_medicaid_category_threshold => "52601.0",
             :medicaid_chip_category => "CHIP Targeted Low Income Child",
             :medicaid_chip_category_threshold => "69161.0",
             :category_determinations =>
              [{:category => "Residency",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Adult Group Category",
                :indicator_code => false,
                :ineligibility_code => 123,
                :ineligibility_reason =>
                 "Applicant is not between the ages of 19 and 64 (inclusive)"},
               {:category => "Parent Caretaker Category",
                :indicator_code => false,
                :ineligibility_code => 146,
                :ineligibility_reason =>
                 "No child met all criteria for parent caretaker category"},
               {:category => "Pregnancy Category",
                :indicator_code => false,
                :ineligibility_code => 124,
                :ineligibility_reason =>
                 "Applicant not pregnant or within postpartum period"},
               {:category => "Child Category",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Optional Targeted Low Income Child",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "CHIP Targeted Low Income Child",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Unborn Child",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Income Medicaid Eligible",
                :indicator_code => false,
                :ineligibility_code => 402,
                :ineligibility_reason =>
                 "Applicant's income is greater than the threshold for all eligible categories"},
               {:category => "Income CHIP Eligible",
                :indicator_code => false,
                :ineligibility_code => 402,
                :ineligibility_reason =>
                 "Applicant's income is greater than the threshold for all eligible categories"},
               {:category => "Medicaid CHIPRA 214",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "CHIP CHIPRA 214",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Trafficking Victim",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Seven Year Limit",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Five Year Bar",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Title II Work Quarters Met",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Medicaid Citizen Or Immigrant",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "CHIP Citizen Or Immigrant",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Former Foster Care Category",
                :indicator_code => false,
                :ineligibility_code => 400,
                :ineligibility_reason =>
                 "Applicant was not formerly in foster care"},
               {:category => "Work Quarters Override Income",
                :indicator_code => false,
                :ineligibility_code => 340,
                :ineligibility_reason => "Income is greater than 100% FPL"},
               {:category => "State Health Benefits CHIP",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "CHIP Waiting Period Satisfied",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Dependent Child Covered",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Medicaid Non-MAGI Referral",
                :indicator_code => false,
                :ineligibility_code => 108,
                :ineligibility_reason =>
                 "Applicant does not meet requirements for a non-MAGI referral"},
               {:category => "Emergency Medicaid",
                :indicator_code => false,
                :ineligibility_code => 109,
                :ineligibility_reason =>
                 "Applicant does not meet the eligibility criteria for emergency Medicaid"},
               {:category => "Refugee Medical Assistance",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "APTC Referral",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil}]},
           :applicant_reference =>
            {:first_name => "childtest3",
             :last_name => "test",
             :dob => "2021-01-01",
             :person_hbx_id => "200201361",
             :encrypted_ssn => "fakBWDUfwvztdoXP5kINVoMAvf0FLcVIkw==\n"}},
          {:product_eligibility_determination =>
            {:is_ia_eligible => true,
             :is_medicaid_chip_eligible => false,
             :is_totally_ineligible => nil,
             :is_magi_medicaid => false,
             :is_uqhp_eligible => nil,
             :is_csr_eligible => true,
             :csr => "73",
             :is_non_magi_medicaid_eligible => false,
             :is_without_assistance => false,
             :magi_medicaid_monthly_household_income => "70000.0",
             :medicaid_household_size => 5,
             :magi_medicaid_monthly_income_limit => "0.0",
             :magi_as_percentage_of_fpl => "215.0",
             :magi_medicaid_category => "child",
             :magi_medicaid_ineligibility_reasons =>
              ["Applicant's MAGI above the threshold for category"],
             :is_eligible_for_non_magi_reasons => false,
             :chip_ineligibility_reasons =>
              ["Applicant's MAGI above the threshold for category"],
             :magi_medicaid_category_threshold => "52601.0",
             :medicaid_chip_category => "CHIP Targeted Low Income Child",
             :medicaid_chip_category_threshold => "69161.0",
             :category_determinations =>
              [{:category => "Residency",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Adult Group Category",
                :indicator_code => false,
                :ineligibility_code => 123,
                :ineligibility_reason =>
                 "Applicant is not between the ages of 19 and 64 (inclusive)"},
               {:category => "Parent Caretaker Category",
                :indicator_code => false,
                :ineligibility_code => 146,
                :ineligibility_reason =>
                 "No child met all criteria for parent caretaker category"},
               {:category => "Pregnancy Category",
                :indicator_code => false,
                :ineligibility_code => 124,
                :ineligibility_reason =>
                 "Applicant not pregnant or within postpartum period"},
               {:category => "Child Category",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Optional Targeted Low Income Child",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "CHIP Targeted Low Income Child",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Unborn Child",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Income Medicaid Eligible",
                :indicator_code => false,
                :ineligibility_code => 402,
                :ineligibility_reason =>
                 "Applicant's income is greater than the threshold for all eligible categories"},
               {:category => "Income CHIP Eligible",
                :indicator_code => false,
                :ineligibility_code => 402,
                :ineligibility_reason =>
                 "Applicant's income is greater than the threshold for all eligible categories"},
               {:category => "Medicaid CHIPRA 214",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "CHIP CHIPRA 214",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Trafficking Victim",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Seven Year Limit",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Five Year Bar",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Title II Work Quarters Met",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Medicaid Citizen Or Immigrant",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "CHIP Citizen Or Immigrant",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Former Foster Care Category",
                :indicator_code => false,
                :ineligibility_code => 400,
                :ineligibility_reason =>
                 "Applicant was not formerly in foster care"},
               {:category => "Work Quarters Override Income",
                :indicator_code => false,
                :ineligibility_code => 340,
                :ineligibility_reason => "Income is greater than 100% FPL"},
               {:category => "State Health Benefits CHIP",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "CHIP Waiting Period Satisfied",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Dependent Child Covered",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "Medicaid Non-MAGI Referral",
                :indicator_code => false,
                :ineligibility_code => 108,
                :ineligibility_reason =>
                 "Applicant does not meet requirements for a non-MAGI referral"},
               {:category => "Emergency Medicaid",
                :indicator_code => false,
                :ineligibility_code => 109,
                :ineligibility_reason =>
                 "Applicant does not meet the eligibility criteria for emergency Medicaid"},
               {:category => "Refugee Medical Assistance",
                :indicator_code => nil,
                :ineligibility_code => nil,
                :ineligibility_reason => nil},
               {:category => "APTC Referral",
                :indicator_code => true,
                :ineligibility_code => nil,
                :ineligibility_reason => nil}]},
           :applicant_reference =>
            {:first_name => "childtest4",
             :last_name => "test",
             :dob => "2021-01-01",
             :person_hbx_id => "200201362",
             :encrypted_ssn => "Stc/ycLO5WsL+M99+beqgIMFvv0EL8ZKkA==\n"}}],
        :annual_tax_household_income => "70000.0",
        :csr_annual_income_limit => "730940000.0",
        :effective_on => "2022-11-01",
        :determined_on => "2022-10-14",
        :yearly_expected_contribution => "2114.0"}],
     :relationships =>
      [{:kind => "child",
        :applicant_reference =>
         {:first_name => "childtest1",
          :last_name => "test",
          :dob => "2019-01-01",
          :person_hbx_id => "200201358",
          :encrypted_ssn => "1/WLnrxXDTUE4mi98BGIUoMFu/wGL8RNkg==\n"},
        :relative_reference =>
         {:first_name => "adult2.1",
          :last_name => "test",
          :dob => "2000-01-01",
          :person_hbx_id => "200201355",
          :encrypted_ssn => "qfl5FpLXZtCR5omSMxhi6IMGvP8HLMVJlA==\n"}},
       {:kind => "parent",
        :applicant_reference =>
         {:first_name => "adult2.1",
          :last_name => "test",
          :dob => "2000-01-01",
          :person_hbx_id => "200201355",
          :encrypted_ssn => "qfl5FpLXZtCR5omSMxhi6IMGvP8HLMVJlA==\n"},
        :relative_reference =>
         {:first_name => "childtest1",
          :last_name => "test",
          :dob => "2019-01-01",
          :person_hbx_id => "200201358",
          :encrypted_ssn => "1/WLnrxXDTUE4mi98BGIUoMFu/wGL8RNkg==\n"}},
       {:kind => "child",
        :applicant_reference =>
         {:first_name => "childtest2",
          :last_name => "test",
          :dob => "2020-01-01",
          :person_hbx_id => "200201360",
          :encrypted_ssn => "hsytIzg+XFT+SPvdinpoEYMHvvwGL8JLkw==\n"},
        :relative_reference =>
         {:first_name => "adult2.1",
          :last_name => "test",
          :dob => "2000-01-01",
          :person_hbx_id => "200201355",
          :encrypted_ssn => "qfl5FpLXZtCR5omSMxhi6IMGvP8HLMVJlA==\n"}},
       {:kind => "parent",
        :applicant_reference =>
         {:first_name => "adult2.1",
          :last_name => "test",
          :dob => "2000-01-01",
          :person_hbx_id => "200201355",
          :encrypted_ssn => "qfl5FpLXZtCR5omSMxhi6IMGvP8HLMVJlA==\n"},
        :relative_reference =>
         {:first_name => "childtest2",
          :last_name => "test",
          :dob => "2020-01-01",
          :person_hbx_id => "200201360",
          :encrypted_ssn => "hsytIzg+XFT+SPvdinpoEYMHvvwGL8JLkw==\n"}},
       {:kind => "child",
        :applicant_reference =>
         {:first_name => "childtest3",
          :last_name => "test",
          :dob => "2021-01-01",
          :person_hbx_id => "200201361",
          :encrypted_ssn => "fakBWDUfwvztdoXP5kINVoMAvf0FLcVIkw==\n"},
        :relative_reference =>
         {:first_name => "adult2.1",
          :last_name => "test",
          :dob => "2000-01-01",
          :person_hbx_id => "200201355",
          :encrypted_ssn => "qfl5FpLXZtCR5omSMxhi6IMGvP8HLMVJlA==\n"}},
       {:kind => "parent",
        :applicant_reference =>
         {:first_name => "adult2.1",
          :last_name => "test",
          :dob => "2000-01-01",
          :person_hbx_id => "200201355",
          :encrypted_ssn => "qfl5FpLXZtCR5omSMxhi6IMGvP8HLMVJlA==\n"},
        :relative_reference =>
         {:first_name => "childtest3",
          :last_name => "test",
          :dob => "2021-01-01",
          :person_hbx_id => "200201361",
          :encrypted_ssn => "fakBWDUfwvztdoXP5kINVoMAvf0FLcVIkw==\n"}},
       {:kind => "child",
        :applicant_reference =>
         {:first_name => "childtest4",
          :last_name => "test",
          :dob => "2021-01-01",
          :person_hbx_id => "200201362",
          :encrypted_ssn => "Stc/ycLO5WsL+M99+beqgIMFvv0EL8ZKkA==\n"},
        :relative_reference =>
         {:first_name => "adult2.1",
          :last_name => "test",
          :dob => "2000-01-01",
          :person_hbx_id => "200201355",
          :encrypted_ssn => "qfl5FpLXZtCR5omSMxhi6IMGvP8HLMVJlA==\n"}},
       {:kind => "parent",
        :applicant_reference =>
         {:first_name => "adult2.1",
          :last_name => "test",
          :dob => "2000-01-01",
          :person_hbx_id => "200201355",
          :encrypted_ssn => "qfl5FpLXZtCR5omSMxhi6IMGvP8HLMVJlA==\n"},
        :relative_reference =>
         {:first_name => "childtest4",
          :last_name => "test",
          :dob => "2021-01-01",
          :person_hbx_id => "200201362",
          :encrypted_ssn => "Stc/ycLO5WsL+M99+beqgIMFvv0EL8ZKkA==\n"}},
       {:kind => "sibling",
        :applicant_reference =>
         {:first_name => "childtest1",
          :last_name => "test",
          :dob => "2019-01-01",
          :person_hbx_id => "200201358",
          :encrypted_ssn => "1/WLnrxXDTUE4mi98BGIUoMFu/wGL8RNkg==\n"},
        :relative_reference =>
         {:first_name => "childtest2",
          :last_name => "test",
          :dob => "2020-01-01",
          :person_hbx_id => "200201360",
          :encrypted_ssn => "hsytIzg+XFT+SPvdinpoEYMHvvwGL8JLkw==\n"}},
       {:kind => "sibling",
        :applicant_reference =>
         {:first_name => "childtest2",
          :last_name => "test",
          :dob => "2020-01-01",
          :person_hbx_id => "200201360",
          :encrypted_ssn => "hsytIzg+XFT+SPvdinpoEYMHvvwGL8JLkw==\n"},
        :relative_reference =>
         {:first_name => "childtest1",
          :last_name => "test",
          :dob => "2019-01-01",
          :person_hbx_id => "200201358",
          :encrypted_ssn => "1/WLnrxXDTUE4mi98BGIUoMFu/wGL8RNkg==\n"}},
       {:kind => "sibling",
        :applicant_reference =>
         {:first_name => "childtest1",
          :last_name => "test",
          :dob => "2019-01-01",
          :person_hbx_id => "200201358",
          :encrypted_ssn => "1/WLnrxXDTUE4mi98BGIUoMFu/wGL8RNkg==\n"},
        :relative_reference =>
         {:first_name => "childtest3",
          :last_name => "test",
          :dob => "2021-01-01",
          :person_hbx_id => "200201361",
          :encrypted_ssn => "fakBWDUfwvztdoXP5kINVoMAvf0FLcVIkw==\n"}},
       {:kind => "sibling",
        :applicant_reference =>
         {:first_name => "childtest3",
          :last_name => "test",
          :dob => "2021-01-01",
          :person_hbx_id => "200201361",
          :encrypted_ssn => "fakBWDUfwvztdoXP5kINVoMAvf0FLcVIkw==\n"},
        :relative_reference =>
         {:first_name => "childtest1",
          :last_name => "test",
          :dob => "2019-01-01",
          :person_hbx_id => "200201358",
          :encrypted_ssn => "1/WLnrxXDTUE4mi98BGIUoMFu/wGL8RNkg==\n"}},
       {:kind => "sibling",
        :applicant_reference =>
         {:first_name => "childtest2",
          :last_name => "test",
          :dob => "2020-01-01",
          :person_hbx_id => "200201360",
          :encrypted_ssn => "hsytIzg+XFT+SPvdinpoEYMHvvwGL8JLkw==\n"},
        :relative_reference =>
         {:first_name => "childtest3",
          :last_name => "test",
          :dob => "2021-01-01",
          :person_hbx_id => "200201361",
          :encrypted_ssn => "fakBWDUfwvztdoXP5kINVoMAvf0FLcVIkw==\n"}},
       {:kind => "sibling",
        :applicant_reference =>
         {:first_name => "childtest3",
          :last_name => "test",
          :dob => "2021-01-01",
          :person_hbx_id => "200201361",
          :encrypted_ssn => "fakBWDUfwvztdoXP5kINVoMAvf0FLcVIkw==\n"},
        :relative_reference =>
         {:first_name => "childtest2",
          :last_name => "test",
          :dob => "2020-01-01",
          :person_hbx_id => "200201360",
          :encrypted_ssn => "hsytIzg+XFT+SPvdinpoEYMHvvwGL8JLkw==\n"}},
       {:kind => "sibling",
        :applicant_reference =>
         {:first_name => "childtest1",
          :last_name => "test",
          :dob => "2019-01-01",
          :person_hbx_id => "200201358",
          :encrypted_ssn => "1/WLnrxXDTUE4mi98BGIUoMFu/wGL8RNkg==\n"},
        :relative_reference =>
         {:first_name => "childtest4",
          :last_name => "test",
          :dob => "2021-01-01",
          :person_hbx_id => "200201362",
          :encrypted_ssn => "Stc/ycLO5WsL+M99+beqgIMFvv0EL8ZKkA==\n"}},
       {:kind => "sibling",
        :applicant_reference =>
         {:first_name => "childtest4",
          :last_name => "test",
          :dob => "2021-01-01",
          :person_hbx_id => "200201362",
          :encrypted_ssn => "Stc/ycLO5WsL+M99+beqgIMFvv0EL8ZKkA==\n"},
        :relative_reference =>
         {:first_name => "childtest1",
          :last_name => "test",
          :dob => "2019-01-01",
          :person_hbx_id => "200201358",
          :encrypted_ssn => "1/WLnrxXDTUE4mi98BGIUoMFu/wGL8RNkg==\n"}},
       {:kind => "sibling",
        :applicant_reference =>
         {:first_name => "childtest2",
          :last_name => "test",
          :dob => "2020-01-01",
          :person_hbx_id => "200201360",
          :encrypted_ssn => "hsytIzg+XFT+SPvdinpoEYMHvvwGL8JLkw==\n"},
        :relative_reference =>
         {:first_name => "childtest4",
          :last_name => "test",
          :dob => "2021-01-01",
          :person_hbx_id => "200201362",
          :encrypted_ssn => "Stc/ycLO5WsL+M99+beqgIMFvv0EL8ZKkA==\n"}},
       {:kind => "sibling",
        :applicant_reference =>
         {:first_name => "childtest4",
          :last_name => "test",
          :dob => "2021-01-01",
          :person_hbx_id => "200201362",
          :encrypted_ssn => "Stc/ycLO5WsL+M99+beqgIMFvv0EL8ZKkA==\n"},
        :relative_reference =>
         {:first_name => "childtest2",
          :last_name => "test",
          :dob => "2020-01-01",
          :person_hbx_id => "200201360",
          :encrypted_ssn => "hsytIzg+XFT+SPvdinpoEYMHvvwGL8JLkw==\n"}},
       {:kind => "sibling",
        :applicant_reference =>
         {:first_name => "childtest3",
          :last_name => "test",
          :dob => "2021-01-01",
          :person_hbx_id => "200201361",
          :encrypted_ssn => "fakBWDUfwvztdoXP5kINVoMAvf0FLcVIkw==\n"},
        :relative_reference =>
         {:first_name => "childtest4",
          :last_name => "test",
          :dob => "2021-01-01",
          :person_hbx_id => "200201362",
          :encrypted_ssn => "Stc/ycLO5WsL+M99+beqgIMFvv0EL8ZKkA==\n"}},
       {:kind => "sibling",
        :applicant_reference =>
         {:first_name => "childtest4",
          :last_name => "test",
          :dob => "2021-01-01",
          :person_hbx_id => "200201362",
          :encrypted_ssn => "Stc/ycLO5WsL+M99+beqgIMFvv0EL8ZKkA==\n"},
        :relative_reference =>
         {:first_name => "childtest3",
          :last_name => "test",
          :dob => "2021-01-01",
          :person_hbx_id => "200201361",
          :encrypted_ssn => "fakBWDUfwvztdoXP5kINVoMAvf0FLcVIkw==\n"}}],
     :us_state => "ME",
     :hbx_id => "200200928",
     :oe_start_on => "2021-11-01",
     :notice_options =>
      {:send_eligibility_notices => true,
       :send_open_enrollment_notices => false,
       :paper_notification => true},
     :mitc_households =>
      [{:household_id => "1",
        :people =>
         [{:person_id => 200_201_355},
          {:person_id => 200_201_358},
          {:person_id => 200_201_360},
          {:person_id => 200_201_361},
          {:person_id => 200_201_362}]}],
     :mitc_tax_returns =>
      [{:filers => [{:person_id => 200_201_355}],
        :dependents =>
     [{:person_id => 200_201_358},
      {:person_id => 200_201_360},
      {:person_id => 200_201_361},
      {:person_id => 200_201_362}]}],
     :submitted_at => "2022-10-14T13:36:03.887+00:00"}
  end

  let(:mm_application_entity) { ::AcaEntities::MagiMedicaid::Operations::InitializeApplication.new.call(response_payload_1).success }

  let(:primary_dob) { mm_application_entity.primary_applicant.demographic.dob.to_date  }
  let(:person) { FactoryBot.create(:person, :with_consumer_role, first_name: 'adult2.1', last_name: 'test', dob: primary_dob, hbx_id: '200201355') }
  let(:family) { FactoryBot.create(:family, :with_primary_family_member, person: person) }
  let!(:application) { FactoryBot.create(:financial_assistance_application, hbx_id: '200200928', aasm_state: "submitted", family_id: family.id, effective_date: TimeKeeper.date_of_record) }
  let!(:ed) do
    eli_d = FactoryBot.create(:financial_assistance_eligibility_determination, application: application)
    eli_d.update_attributes!(hbx_assigned_id: '118825')
    eli_d
  end
  let!(:applicant) do
    FactoryBot.create(:financial_assistance_applicant,
                      eligibility_determination_id: ed.id,
                      person_hbx_id: person.hbx_id,
                      is_primary_applicant: true,
                      first_name: 'adult2.1',
                      last_name: 'test',
                      dob: primary_dob,
                      application: application)
  end

  let!(:create_members_data) do
    non_primary_applicants = mm_application_entity.applicants.select { |a| a.is_primary_applicant == false}
    non_primary_applicants.each do |applicant|
      name_data = applicant.name
      demographics = applicant.demographic
      applicant_person = FactoryBot.create(:person, :with_consumer_role,
                                           :first_name => name_data.first_name,
                                           :last_name => name_data.last_name,
                                           :dob => demographics.dob.to_date,
                                           :hbx_id => applicant.person_hbx_id)

      FactoryBot.create(:family_member, family: family, person: applicant_person)

      FactoryBot.create(:financial_assistance_applicant,
                        eligibility_determination_id: ed.id,
                        person_hbx_id: applicant_person.hbx_id,
                        is_primary_applicant: true,
                        first_name: name_data.first_name,
                        last_name: name_data.last_name,
                        dob: demographics.dob.to_date,
                        application: application)

      family.person.person_relationships << PersonRelationship.new(relative_id: applicant_person.id, kind: 'child')
      family.save!
    end
  end

  let!(:county_zip) { ::BenefitMarkets::Locations::CountyZip.create!(county_name: 'Hampden', zip: '01001', state: 'DC') }
  let!(:rating_area) do
    ::BenefitMarkets::Locations::RatingArea.create!(active_year: TimeKeeper.date_of_record.year, exchange_provided_code: "R-ME001", county_zip_ids: [county_zip.id], covered_states: [county_zip.state])
  end
  let!(:service_area) do
    ::BenefitMarkets::Locations::ServiceArea.create!(active_year: TimeKeeper.date_of_record.year, county_zip_ids: [county_zip.id], issuer_provided_code: "MES002", issuer_profile_id: BSON::ObjectId.new)
  end
end
