---
registry:
  - namespace:
    - :enroll_app
    - :aca_individual_market
    - :financial_assistance
    features:
      - key: :aceds_curam
        item: :aceds_curam
        is_enabled: false
      - key: :ivl_application_checklist
        is_enabled: true
        item: :ivl_application_checklist
        settings:
          - key: :file_location
            item: 'db/documents/ivl_checklist.pdf'
      - key: :enrollment_dates
        item: :enrollment_dates
        is_enabled: true
        settings:
          - key: :application_new_year_effective_date_day_of_month
            item: 1
          - key: :application_new_year_effective_date_month_of_year
            item: 11
          - key: :enrollment_due_day_of_month
            is_enabled: true
            item: 15
          - key: :earliest_effective_date
            item: FinancialAssistance::Operations::EnrollmentDates::EarliestEffectiveDate
            is_enabled: true
          - key: :application_year
            item: FinancialAssistance::Operations::EnrollmentDates::ApplicationYear
            is_enabled: true
      - key: :benchmark_plans
        item: :benchmark_plans
        is_enabled: true
        settings:
          - key: :benchmark_plan_2020
            item: true
            settings:
              - key: :name
                item: 'Plan Name'
              - key: :hios_id
                item: 'HIOS-ID'
              - key: :is_dental_only
                item: false
              - key: :metal_level
                item: :silver
              - key: :coverage_kind
                item: :health
              - key: :ehb
                item: 0.80
              - key: :carrier_name
                item: "Carrier Name"
      - key: :unemployment_income
        item: :unemployment_income
        is_enabled: true
      - key: :indian_health_service_question
        is_enabled: false
      - key: :mainecare_healthcare_questions
        is_enabled: true
  - namespace:
    - :documents
    features:
      - key: :consumer_validations
        is_enabled: false
      - key: :non_magi_referral_display
        is_enabled: false
  - namespace:
    - :questions
    features:
    - key: :has_enrolled_health_coverage
      is_enabled: true
      settings:
        - key: :currently_enrolled
          item: true
        - key: :currently_enrolled_with_hra
          item: false
    - key: :has_eligible_health_coverage
      is_enabled: true
      settings:
        - key: :currently_eligible
          item: true
        - key: :currently_eligible_with_hra
          item: false
    - key: :has_medicare_cubcare_eligible
      is_enabled: false
    - key: :medicaid_chip_driver_questions
      is_enabled: false
      settings:
        - key: :medicaid_chip
          item: "Medicaid"
    - key: :net_annual_income_display
      is_enabled: false
    - key: :has_dependent_with_coverage
      is_enabled: false
    - key: :private_individual_and_family_coverage
      is_enabled: true
    - key: :acf_refugee_medical_assistance
      is_enabled: true
    - key: :americorps_health_benefits
      is_enabled: true
    - key: :child_health_insurance_plan
      is_enabled: true
    - key: :medicaid
      is_enabled: true
    - key: :medicare
      is_enabled: true
    - key: :medicare_advantage
      is_enabled: true
    - key: :medicare_part_b
      is_enabled: true
    - key: :state_supplementary_payment
      is_enabled: true
    - key: :tricare
      is_enabled: true
    - key: :veterans_benefits
      is_enabled: true
    - key: :naf_health_benefit_program
      is_enabled: true
    - key: :health_care_for_peace_corp_volunteers
      is_enabled: true
    - key: :department_of_defense_non_appropriated_health_benefits
      is_enabled: true
    - key: :cobra_benefit_fa
      is_enabled: true
    - key: :employer_sponsored_insurance
      is_enabled: true
    - key: :self_funded_student_health_coverage
      is_enabled: true
    - key: :foreign_government_health_coverage
      is_enabled: true
    - key: :private_health_insurance_plan
      is_enabled: true
    - key: :coverage_obtained_through_another_exchange
      is_enabled: true
    - key: :coverage_under_the_state_health_benefits_risk_pool
      is_enabled: true
    - key: :veterans_administration_health_benefits
      is_enabled: true
    - key: :peace_corps_health_benefits
      is_enabled: true
    - key: :health_reimbursement_arrangement # new
      is_enabled: false
    - key: :retiree_health_benefits # new
      is_enabled: false
    - key: :other_full_benefit_coverage # new
      is_enabled: false
    - key: :other_limited_benefit_coverage # new
      is_enabled: false
    - key: :prize_and_awards
      is_enabled: true
      settings:
        - key: :gamble_prize
          item: false
    - key: :full_medicaid_determination_step
      is_enabled: true
# TODO eligibility engine connectivity(HAVEN) settings
# TODO mec service connectivity settings
