---
registry:
  - namespace:
      - :css_components
    features:
      - key: :qle_carousel
        is_enabled: true
        settings:
          - key: :color
            item: '#007bc4'
      - key: :ivl_notice_footer
        is_enabled: true
        settings:
          - key: :color
            item: '#333333'