---
registry:
  - namespace:
      - :fdsh_services
    features:
      - key: :ridp_h139
        is_enabled: true
      - key: :paper_application_verification
        is_enabled: true
      - key: :vlp_h92
        is_enabled: true
      - key: :ssa_h3
        is_enabled: true
        settings:
        - key: :payload_type
          item:  <%= ENV['SSA_H3_PAYLOAD_TYPE'] || "xml" %>
      - key: :renewal_eligibility_verification_using_rrv
        item: :renewal_eligibility_verification_using_rrv
        is_enabled: <%= ENV['RENEWAL_ELIGIBILITY_VERIFICATION_USING_RRV_IS_ENABLED'] || false %>
      - key: :validate_and_record_publish_errors
        is_enabled: <%= ENV['VALIDATE_AND_RECORD_PUBLISH_ERRORS_IS_ENABLED'] || false %>
      - key: :validate_and_record_publish_application_errors
        is_enabled: <%= ENV['VALIDATE_AND_RECORD_PUBLISH_APPLICATION_ERRORS_IS_ENABLED'] || false %>
        settings:
          - key: :csr_codes
            item:  <%= ENV['FDSH_HUB_CALL_APPLICATION_ERROR_CSR_CODES'] || ["02", "04", "05", "06"] %>
        is_enabled: <%= ENV['RENEWAL_ELIGIBILITY_VERIFICATION_USING_RRV_IS_ENABLED'] || false %>
