---
registry:
  - namespace:
      - :identity_management
    features:
      - key: :identity_management_config
        is_enabled: true
        settings:
          - key: :identity_manager
            item: :keycloak
      - key: :auth_url
        is_enabled: true
        item: "https://keycloak/auth/realms/sbe_business_operations/protocol/saml/clients/polypress"
