---
registry:
  - namespace:
      - :enroll_app
    features:
      - key: :aca_shop_market
        is_enabled: true
      - key: :fehb_market
        is_enabled: true
      - key: :aca_individual_market
        is_enabled: true