---
registry:
  - namespace:
      - :enroll_app
    features:
      - key: :shop_market
        is_enabled: false
      - key: :fehb
        is_enabled: false
      - key: :individual_market
        is_enabled: true