name: Daily Tools Summary

on:
    push:
    workflow_dispatch:
    # schedule:
    #   - cron: "0 0 * * *"

jobs:
    daily-tools-summary:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            # - name: Download CodeQL artifact
            #   uses: actions/download-artifact@v2
            #   with:
            #       name: codeql-results

            # - name: Download Coverage Report
            #   uses: actions/download-artifact@v4
            #   with:
            #       name: code-coverage-report
            #       repository: ideacrew/enroll
            #       github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: "Download artifact"
              run: |
                OTHER_REPO="ideacrew/enroll"
                WF_NAME="full-suite.yml"
                ARTIFACT_NAME="code-coverage-report"
                RUN_ID=`gh run --repo ${OTHER_REPO} list --workflow ${WF_NAME} --json databaseId --jq .[0].databaseId`
                gh run --repo ${OTHER_REPO} download ${RUN_ID} -n ${ARTIFACT_NAME}
      
            - name: figure it out what we have
              run: ls -lha

            - name: Write to Job Summary
              run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY


            # - name: Check status of last full-suite run
            #   run: |
            #       # Add your code here to check the status of the last full-suite run
            #       # You can use the downloaded CodeQL artifact to retrieve the necessary information

            # - name: Create summary
            #   run: |
            #       # Add your code here to create a summary based on the status of the last full-suite run
            #       # You can use the information obtained in the previous step

            # - name: Send Slack message
            #   uses: rtCamp/action-slack-notify@v2
            #   with:
            #       status: ${{ job.status }}
            #       message: |
            #           Summary of the daily tools:
            #           # Add your summary here
