---
registry:
  - namespace:
      - :identity_management
    features:
      - key: :identity_management_config
        is_enabled: false
        settings:
          - key: :identity_manager
            item: :oracle_iam
      - key: :auth_url
        is_enabled: false
        item: ""
