---
registry:
  - namespace:
      - :brokers
    features:
      - key: :brokers
        is_enabled: true
        meta:
          label: Brokers
          content_type: :boolean
          default: true
          description: The Enroll Application provides a dashboard for brokers where they may access and manage client employers and their employees. A broker’s account allows the broker to see all of his or her small group and individual clients. The broker is able to access employer, employee, and individual accounts from the dashboard. 
          is_required: true
          is_visible: true
        settings:
          - key: :carrier_appointments
            item: {"Aetna Health Inc": => nil, "Aetna Life Insurance Company": => nil, "Carefirst Bluechoice Inc": => nil, "Group Hospitalization and Medical Services Inc": => nil, "Kaiser Foundation": => nil, "Optimum Choice": => nil, "United Health Care Insurance": => nil, "United Health Care Mid Atlantic": => nil}
      - key: :broker_attestation_fields
        item: :broker_attestation_fields
        is_enabled: false